const utils = require("./utils");
const dbApiScripts = require("./dbApiScripts");

module.exports = {
  createInviteLink: utils.createInviteLink,
  createBulkInviteLink: utils.createBulkInviteLink,
  getIdListOfInviteLinkByField: utils.getIdListOfInviteLinkByField,
  getInviteLinkById: utils.getInviteLinkById,
  getInviteLinkAggById: utils.getInviteLinkAggById,
  getInviteLinkListByQuery: utils.getInviteLinkListByQuery,
  getInviteLinkListByMQuery: utils.getInviteLinkListByMQuery,
  getInviteLinkStatsByQuery: utils.getInviteLinkStatsByQuery,
  getInviteLinkStatsByMQuery: utils.getInviteLinkStatsByMQuery,
  getInviteLinkByQuery: utils.getInviteLinkByQuery,
  getInviteLinkByMQuery: utils.getInviteLinkByMQuery,
  updateInviteLinkById: utils.updateInviteLinkById,
  updateInviteLinkByIdList: utils.updateInviteLinkByIdList,
  updateInviteLinkByQuery: utils.updateInviteLinkByQuery,
  updateInviteLinkByMQuery: utils.updateInviteLinkByMQuery,
  deleteInviteLinkById: utils.deleteInviteLinkById,
  deleteInviteLinkByQuery: utils.deleteInviteLinkByQuery,
  deleteInviteLinkByMQuery: utils.deleteInviteLinkByMQuery,
  getInviteLinkByInviteCode: utils.getInviteLinkByInviteCode,
  dbScriptCreateInvitelink: dbApiScripts.dbScriptCreateInvitelink,
  dbScriptActivateInvitelink: dbApiScripts.dbScriptActivateInvitelink,
  dbScriptRevokeInvitelink: dbApiScripts.dbScriptRevokeInvitelink,
  dbScriptDeliverInviteemail: dbApiScripts.dbScriptDeliverInviteemail,
  dbScriptValidateInvitecode: dbApiScripts.dbScriptValidateInvitecode,
  dbScriptConsumeInvitelink: dbApiScripts.dbScriptConsumeInvitelink,
  dbScriptGetInvitelinkbycode: dbApiScripts.dbScriptGetInvitelinkbycode,
  dbScriptGetInvitelink: dbApiScripts.dbScriptGetInvitelink,
  dbScriptListInvitelinks: dbApiScripts.dbScriptListInvitelinks,
  dbScript_fetchListinvitelink: dbApiScripts.dbScript_fetchListinvitelink,
};
