const mealLogFunctions = require("./mealLog");
const mealLineFunctions = require("./mealLine");
const nutritionDayFunctions = require("./nutritionDay");

module.exports = {
  // mealTracker Database
  createMealLog: mealLogFunctions.createMealLog,
  createBulkMealLog: mealLogFunctions.createBulkMealLog,
  getIdListOfMealLogByField: mealLogFunctions.getIdListOfMealLogByField,
  getMealLogById: mealLogFunctions.getMealLogById,
  getMealLogAggById: mealLogFunctions.getMealLogAggById,
  getMealLogListByQuery: mealLogFunctions.getMealLogListByQuery,
  getMealLogListByMQuery: mealLogFunctions.getMealLogListByMQuery,
  getMealLogStatsByQuery: mealLogFunctions.getMealLogStatsByQuery,
  getMealLogStatsByMQuery: mealLogFunctions.getMealLogStatsByMQuery,
  getMealLogByQuery: mealLogFunctions.getMealLogByQuery,
  getMealLogByMQuery: mealLogFunctions.getMealLogByMQuery,
  updateMealLogById: mealLogFunctions.updateMealLogById,
  updateMealLogByIdList: mealLogFunctions.updateMealLogByIdList,
  updateMealLogByQuery: mealLogFunctions.updateMealLogByQuery,
  updateMealLogByMQuery: mealLogFunctions.updateMealLogByMQuery,
  deleteMealLogById: mealLogFunctions.deleteMealLogById,
  deleteMealLogByQuery: mealLogFunctions.deleteMealLogByQuery,
  deleteMealLogByMQuery: mealLogFunctions.deleteMealLogByMQuery,
  dbScriptCreateMeallog: mealLogFunctions.dbScriptCreateMeallog,
  dbScriptGetMeallog: mealLogFunctions.dbScriptGetMeallog,
  dbScriptListMeallogs: mealLogFunctions.dbScriptListMeallogs,
  dbScriptUpdateMeallog: mealLogFunctions.dbScriptUpdateMeallog,
  dbScriptDeleteMeallog: mealLogFunctions.dbScriptDeleteMeallog,
  dbScript_fetchListmeallog: mealLogFunctions.dbScript_fetchListmeallog,
  createMealLine: mealLineFunctions.createMealLine,
  createBulkMealLine: mealLineFunctions.createBulkMealLine,
  getIdListOfMealLineByField: mealLineFunctions.getIdListOfMealLineByField,
  getMealLineById: mealLineFunctions.getMealLineById,
  getMealLineAggById: mealLineFunctions.getMealLineAggById,
  getMealLineListByQuery: mealLineFunctions.getMealLineListByQuery,
  getMealLineListByMQuery: mealLineFunctions.getMealLineListByMQuery,
  getMealLineStatsByQuery: mealLineFunctions.getMealLineStatsByQuery,
  getMealLineStatsByMQuery: mealLineFunctions.getMealLineStatsByMQuery,
  getMealLineByQuery: mealLineFunctions.getMealLineByQuery,
  getMealLineByMQuery: mealLineFunctions.getMealLineByMQuery,
  updateMealLineById: mealLineFunctions.updateMealLineById,
  updateMealLineByIdList: mealLineFunctions.updateMealLineByIdList,
  updateMealLineByQuery: mealLineFunctions.updateMealLineByQuery,
  updateMealLineByMQuery: mealLineFunctions.updateMealLineByMQuery,
  deleteMealLineById: mealLineFunctions.deleteMealLineById,
  deleteMealLineByQuery: mealLineFunctions.deleteMealLineByQuery,
  deleteMealLineByMQuery: mealLineFunctions.deleteMealLineByMQuery,
  dbScriptCreateMealline: mealLineFunctions.dbScriptCreateMealline,
  dbScriptUpdateMealline: mealLineFunctions.dbScriptUpdateMealline,
  dbScriptDeleteMealline: mealLineFunctions.dbScriptDeleteMealline,
  dbScriptListMeallines: mealLineFunctions.dbScriptListMeallines,
  dbScript_fetchListmealline: mealLineFunctions.dbScript_fetchListmealline,
  createNutritionDay: nutritionDayFunctions.createNutritionDay,
  createBulkNutritionDay: nutritionDayFunctions.createBulkNutritionDay,
  getIdListOfNutritionDayByField:
    nutritionDayFunctions.getIdListOfNutritionDayByField,
  getNutritionDayById: nutritionDayFunctions.getNutritionDayById,
  getNutritionDayAggById: nutritionDayFunctions.getNutritionDayAggById,
  getNutritionDayListByQuery: nutritionDayFunctions.getNutritionDayListByQuery,
  getNutritionDayListByMQuery:
    nutritionDayFunctions.getNutritionDayListByMQuery,
  getNutritionDayStatsByQuery:
    nutritionDayFunctions.getNutritionDayStatsByQuery,
  getNutritionDayStatsByMQuery:
    nutritionDayFunctions.getNutritionDayStatsByMQuery,
  getNutritionDayByQuery: nutritionDayFunctions.getNutritionDayByQuery,
  getNutritionDayByMQuery: nutritionDayFunctions.getNutritionDayByMQuery,
  updateNutritionDayById: nutritionDayFunctions.updateNutritionDayById,
  updateNutritionDayByIdList: nutritionDayFunctions.updateNutritionDayByIdList,
  updateNutritionDayByQuery: nutritionDayFunctions.updateNutritionDayByQuery,
  updateNutritionDayByMQuery: nutritionDayFunctions.updateNutritionDayByMQuery,
  deleteNutritionDayById: nutritionDayFunctions.deleteNutritionDayById,
  deleteNutritionDayByQuery: nutritionDayFunctions.deleteNutritionDayByQuery,
  deleteNutritionDayByMQuery: nutritionDayFunctions.deleteNutritionDayByMQuery,
  dbScriptGetDailyprogress: nutritionDayFunctions.dbScriptGetDailyprogress,
  dbScriptGetNutritionday: nutritionDayFunctions.dbScriptGetNutritionday,
  dbScriptListNutritiondays: nutritionDayFunctions.dbScriptListNutritiondays,
  dbScriptGetWeeklyanalytics: nutritionDayFunctions.dbScriptGetWeeklyanalytics,
  dbScriptGetMonthlyanalytics:
    nutritionDayFunctions.dbScriptGetMonthlyanalytics,
  dbScriptTriggerDailyremindercheck:
    nutritionDayFunctions.dbScriptTriggerDailyremindercheck,
  dbScriptTriggerDailysummary:
    nutritionDayFunctions.dbScriptTriggerDailysummary,
  dbScript_fetchListnutritionday:
    nutritionDayFunctions.dbScript_fetchListnutritionday,
};
