module.exports = {
  createMealLog: require("./createMealLog"),
  createBulkMealLog: require("./createBulkMealLog"),
  getIdListOfMealLogByField: require("./getIdListOfMealLogByField"),
  getMealLogById: require("./getMealLogById"),
  getMealLogAggById: require("./getMealLogAggById"),
  getMealLogListByQuery: require("./getMealLogListByQuery"),
  getMealLogListByMQuery: require("./getMealLogListByMQuery"),
  getMealLogStatsByQuery: require("./getMealLogStatsByQuery"),
  getMealLogStatsByMQuery: require("./getMealLogStatsByMQuery"),
  getMealLogByQuery: require("./getMealLogByQuery"),
  getMealLogByMQuery: require("./getMealLogByMQuery"),
  updateMealLogById: require("./updateMealLogById"),
  updateMealLogByIdList: require("./updateMealLogByIdList"),
  updateMealLogByQuery: require("./updateMealLogByQuery"),
  updateMealLogByMQuery: require("./updateMealLogByMQuery"),
  deleteMealLogById: require("./deleteMealLogById"),
  deleteMealLogByQuery: require("./deleteMealLogByQuery"),
  deleteMealLogByMQuery: require("./deleteMealLogByMQuery"),
};
