module.exports = {
  createInviteLink: require("./createInviteLink"),
  createBulkInviteLink: require("./createBulkInviteLink"),
  getIdListOfInviteLinkByField: require("./getIdListOfInviteLinkByField"),
  getInviteLinkById: require("./getInviteLinkById"),
  getInviteLinkAggById: require("./getInviteLinkAggById"),
  getInviteLinkListByQuery: require("./getInviteLinkListByQuery"),
  getInviteLinkListByMQuery: require("./getInviteLinkListByMQuery"),
  getInviteLinkStatsByQuery: require("./getInviteLinkStatsByQuery"),
  getInviteLinkStatsByMQuery: require("./getInviteLinkStatsByMQuery"),
  getInviteLinkByQuery: require("./getInviteLinkByQuery"),
  getInviteLinkByMQuery: require("./getInviteLinkByMQuery"),
  updateInviteLinkById: require("./updateInviteLinkById"),
  updateInviteLinkByIdList: require("./updateInviteLinkByIdList"),
  updateInviteLinkByQuery: require("./updateInviteLinkByQuery"),
  updateInviteLinkByMQuery: require("./updateInviteLinkByMQuery"),
  deleteInviteLinkById: require("./deleteInviteLinkById"),
  deleteInviteLinkByQuery: require("./deleteInviteLinkByQuery"),
  deleteInviteLinkByMQuery: require("./deleteInviteLinkByMQuery"),
  getInviteLinkByInviteCode: require("./getInviteLinkByInviteCode"),
};
