/**
 * DbBucket Router — Auto-generated upload/download routes for database-backed file storage.
 * Generated by Mindbricks Genesis Engine.
 *
 * Buckets: userAvatars
 */
const express = require("express");
const multer = require("multer");
const crypto = require("crypto");
const router = express.Router();
const { scanBuffer: clamavScan } = require("./clamav-scanner");
// Magic-byte sniffer — guards against clients lying about Content-Type.
// `file-type` is an ESM-only package; we dynamic-import it lazily to keep
// this CJS module compatible.
let _fileTypeMod = null;
async function sniffMime(buffer) {
  if (!_fileTypeMod) {
    _fileTypeMod = await import("file-type");
  }
  const result = await _fileTypeMod.fileTypeFromBuffer(buffer);
  return result ? result.mime : null;
}

const createServiceController = require("../controllers-layer/rest-layer/create-service-controller");
const {
  createUserAvatarsFile,
  getUserAvatarsFileByQuery,
  deleteUserAvatarsFileById,
} = require("dbLayer");

// Generate a 12-character random access key
function generateAccessKey() {
  return crypto.randomBytes(9).toString("base64url").slice(0, 12);
}

// Resolve session using the standard RestApi controller (same as business APIs)
async function resolveSession(req, res) {
  if (req.session) return;
  try {
    const restController = createServiceController(
      "bucket",
      "bucket",
      req,
      res,
    );
    await restController.init();
  } catch (_) {
    req.session = null;
  }
}

// Auth middleware that requires login
async function requireAuth(req, res, next) {
  try {
    await resolveSession(req, res);
    if (!req.session?.userId) {
      return res
        .status(401)
        .json({ result: "ERR", message: "Authentication required" });
    }
    next();
  } catch (err) {
    return res
      .status(401)
      .json({ result: "ERR", message: "Authentication required" });
  }
}

// Auth middleware that allows unauthenticated access
async function optionalAuth(req, res, next) {
  try {
    await resolveSession(req, res);
  } catch (_) {
    // Continue without auth
  }
  next();
}

// ============================================================================
// Bucket: userAvatars (/bucket/userAvatars) — virus scan: block
// ============================================================================

const userAvatarsUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5242880 },
  fileFilter: (req, file, cb) => {
    const allowed = ["image/png", "image/jpeg", "image/webp", "image/gif"];
    if (allowed.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(
        new Error(
          `File type ${file.mimetype} not allowed. Allowed: ${allowed.join(", ")}`,
        ),
      );
    }
  },
});

// UPLOAD: POST /bucket/userAvatars/upload
router.post(
  "/bucket/userAvatars/upload",
  requireAuth,
  userAvatarsUpload.single("file"),
  async (req, res) => {
    try {
      if (!req.file) {
        return res
          .status(400)
          .json({
            result: "ERR",
            message:
              "No file provided. Use 'file' field in multipart/form-data.",
          });
      }

      const session = req.session || {};

      let effectiveMime = req.file.mimetype;
      // Magic-byte sniff: do NOT trust the client-declared Content-Type.
      // Reject when the sniffed type isn't in the bucket's allowlist. Files
      // whose type can't be detected (plain text, some XML/HTML) are accepted
      // as-is — sniffing is best-effort, the multer fileFilter already filtered
      // the declared mime.
      try {
        const sniffed = await sniffMime(req.file.buffer);
        if (sniffed) {
          const allowed = [
            "image/png",
            "image/jpeg",
            "image/webp",
            "image/gif",
          ];
          if (!allowed.includes(sniffed)) {
            return res.status(400).json({
              result: "ERR",
              message: `File content type ${sniffed} not allowed (declared: ${req.file.mimetype}). Allowed: ${allowed.join(", ")}`,
            });
          }
          effectiveMime = sniffed;
        }
      } catch (sniffErr) {
        console.warn(
          "[DbBucket:userAvatars] mime sniff failed:",
          sniffErr.message,
        );
      }
      // Virus scan via ClamAV INSTREAM. On scan transport failures (timeout,
      // socket error) we treat the file as not-clean so a misconfigured/down
      // scanner can never silently let infected uploads through.
      const scanResult = await clamavScan(req.file.buffer);
      if (!scanResult.clean) {
        return res.status(422).json({
          result: "ERR",
          code: scanResult.infectionName
            ? "VIRUS_DETECTED"
            : "VIRUS_SCAN_FAILED",
          message: scanResult.infectionName
            ? `File rejected: infected with ${scanResult.infectionName}`
            : `File rejected: ${scanResult.error || "scan failed"}`,
          infectionName: scanResult.infectionName || null,
        });
      }

      const fileRecord = {
        fileName: req.file.originalname,
        mimeType: effectiveMime,
        fileSize: req.file.size,
        fileData: req.file.buffer,
        accessKey: generateAccessKey(),
        ownerId: session.userId || null,
        userId: req.body.userId || null,
        scanStatus: scanResult.clean
          ? "clean"
          : scanResult.error
            ? "error"
            : "infected",
        scanResult: scanResult.infectionName || scanResult.error || null,
        scannedAt: scanResult.scannedAt,
        metadata: req.body.metadata
          ? typeof req.body.metadata === "string"
            ? JSON.parse(req.body.metadata)
            : req.body.metadata
          : null,
      };

      const created = await createUserAvatarsFile(fileRecord);

      // Return metadata without the blob
      const { fileData, ...metadata } = created.dataValues || created;
      res.status(201).json({
        status: "OK",
        action: "upload",
        bucket: "userAvatars",
        file: metadata,
      });
    } catch (err) {
      if (err.message && err.message.includes("not allowed")) {
        return res.status(400).json({ result: "ERR", message: err.message });
      }
      if (err.code === "LIMIT_FILE_SIZE") {
        return res
          .status(400)
          .json({
            result: "ERR",
            message: `File exceeds maximum size of 5 MB`,
          });
      }
      console.error("[DbBucket:userAvatars] Upload error:", err.message);
      res
        .status(500)
        .json({ result: "ERR", message: "Upload failed", error: err.message });
    }
  },
);

// DOWNLOAD by ID: GET /bucket/userAvatars/download/:id
router.get(
  "/bucket/userAvatars/download/:id",
  optionalAuth,
  async (req, res) => {
    try {
      const record = await getUserAvatarsFileByQuery({ id: req.params.id });
      if (!record) {
        return res
          .status(404)
          .json({ result: "ERR", message: "File not found" });
      }
      if (record.scanStatus && record.scanStatus !== "clean") {
        return res.status(451).json({
          result: "ERR",
          code: "FILE_QUARANTINED",
          message: `File unavailable: scan status '${record.scanStatus}'`,
        });
      }

      res.set("Content-Type", record.mimeType || "application/octet-stream");
      res.set(
        "Content-Disposition",
        `inline; filename="${encodeURIComponent(record.fileName)}"`,
      );
      res.set("Content-Length", record.fileSize);
      res.send(record.fileData);
    } catch (err) {
      console.error("[DbBucket:userAvatars] Download error:", err.message);
      res.status(500).json({ result: "ERR", message: "Download failed" });
    }
  },
);

// DOWNLOAD by access key: GET /bucket/userAvatars/download/key/:accessKey
router.get(
  "/bucket/userAvatars/download/key/:accessKey",
  optionalAuth,
  async (req, res) => {
    try {
      const record = await getUserAvatarsFileByQuery({
        accessKey: req.params.accessKey,
      });
      if (!record) {
        return res
          .status(404)
          .json({ result: "ERR", message: "File not found or invalid key" });
      }
      if (record.scanStatus && record.scanStatus !== "clean") {
        return res.status(451).json({
          result: "ERR",
          code: "FILE_QUARANTINED",
          message: `File unavailable: scan status '${record.scanStatus}'`,
        });
      }

      res.set("Content-Type", record.mimeType || "application/octet-stream");
      res.set(
        "Content-Disposition",
        `inline; filename="${encodeURIComponent(record.fileName)}"`,
      );
      res.set("Content-Length", record.fileSize);
      res.send(record.fileData);
    } catch (err) {
      console.error("[DbBucket:userAvatars] Key download error:", err.message);
      res.status(500).json({ result: "ERR", message: "Download failed" });
    }
  },
);

module.exports = router;
