/**
 * ClamAV HTTP scanner — auto-generated by Mindbricks Genesis Engine.
 *
 * Used by DbBucket / RemoteBucket upload routes whose bucket config has
 * `virusScan: true`. POSTs the upload buffer to the shared Mindbricks
 * ClamAV HTTP API (`POST /api/v1/scan`, multipart form with field name
 * `FILES`) which fronts a ClamAV instance with virus DB updates +
 * Cloudflare TLS. No npm dep needed — Node 18+ ships `fetch`, `FormData`
 * and `Blob` globally.
 *
 * Override at runtime by setting any of:
 *   CLAMAV_BASE_URL       default: http://clamav.mindbricks.com
 *   CLAMAV_TIMEOUT_MS     default: 30000
 *   CLAMAV_DEFAULT_MODE   default: "block"  (block | quarantine)
 *
 * The deployer emits these env vars automatically when the project sets
 * projectSettings.clamAvSettings.useClamAv = true.
 *
 *  scanBuffer(buf, fileName?) -> Promise<{
 *    clean:         boolean,      // true if ClamAV returned is_infected=false
 *    infectionName: string|null,  // virus signature name(s) when !clean
 *    error:         string|null,  // populated on transport/timeout failure
 *    scannedAt:     Date,
 *    scannerVersion:string,       // "clamav-http"
 *    bytesScanned:  number,
 *  }>
 *
 * Failure policy: any transport-level error (timeout, non-2xx HTTP,
 * unparseable body) returns clean=false with an `error` field set so the
 * upload route's existing "fail closed" behavior keeps holding — a
 * misconfigured / down scanner can never silently pass infected files.
 */

const CLAMAV_BASE_URL = (
  process.env.CLAMAV_BASE_URL || "http://clamav.mindbricks.com"
).replace(/\/+$/, "");
const CLAMAV_TIMEOUT_MS = parseInt(
  process.env.CLAMAV_TIMEOUT_MS || "30000",
  10,
);
const CLAMAV_DEFAULT_MODE = (
  process.env.CLAMAV_DEFAULT_MODE || "block"
).toLowerCase();

async function scanBuffer(buffer, fileName = "upload.bin") {
  const scannedAt = new Date();
  const bytesScanned = buffer ? buffer.length : 0;

  if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
    return {
      clean: true,
      infectionName: null,
      error: null,
      scannedAt,
      scannerVersion: "clamav-http",
      bytesScanned: 0,
    };
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), CLAMAV_TIMEOUT_MS);

  try {
    const form = new FormData();
    // Field name MUST be uppercase "FILES" per the Mindbricks ClamAV API.
    form.append("FILES", new Blob([buffer]), fileName);

    const resp = await fetch(`${CLAMAV_BASE_URL}/api/v1/scan`, {
      method: "POST",
      body: form,
      signal: controller.signal,
    });

    if (!resp.ok) {
      return {
        clean: false,
        infectionName: null,
        error: `ClamAV HTTP ${resp.status} ${resp.statusText}`,
        scannedAt,
        scannerVersion: "clamav-http",
        bytesScanned,
      };
    }

    const data = await resp.json();
    const result = data && data.data && data.data.result && data.data.result[0];

    if (!result) {
      return {
        clean: false,
        infectionName: null,
        error: `Unexpected ClamAV response: ${JSON.stringify(data).slice(0, 200)}`,
        scannedAt,
        scannerVersion: "clamav-http",
        bytesScanned,
      };
    }

    if (result.is_infected) {
      return {
        clean: false,
        infectionName: (result.viruses || []).join(", ") || "unknown",
        error: null,
        scannedAt,
        scannerVersion: "clamav-http",
        bytesScanned,
      };
    }

    return {
      clean: true,
      infectionName: null,
      error: null,
      scannedAt,
      scannerVersion: "clamav-http",
      bytesScanned,
    };
  } catch (err) {
    const reason =
      err.name === "AbortError"
        ? `ClamAV scan timed out after ${CLAMAV_TIMEOUT_MS}ms`
        : `ClamAV request error: ${err.message}`;
    return {
      clean: false,
      infectionName: null,
      error: reason,
      scannedAt,
      scannerVersion: "clamav-http",
      bytesScanned,
    };
  } finally {
    clearTimeout(timer);
  }
}

module.exports = {
  scanBuffer,
  CLAMAV_BASE_URL,
  CLAMAV_TIMEOUT_MS,
  CLAMAV_DEFAULT_MODE,
};
