module.exports = {
  createUserAvatarsFile: require("./createUserAvatarsFile"),
  createBulkUserAvatarsFile: require("./createBulkUserAvatarsFile"),
  getIdListOfUserAvatarsFileByField: require("./getIdListOfUserAvatarsFileByField"),
  getUserAvatarsFileById: require("./getUserAvatarsFileById"),
  getUserAvatarsFileAggById: require("./getUserAvatarsFileAggById"),
  getUserAvatarsFileListByQuery: require("./getUserAvatarsFileListByQuery"),
  getUserAvatarsFileListByMQuery: require("./getUserAvatarsFileListByMQuery"),
  getUserAvatarsFileStatsByQuery: require("./getUserAvatarsFileStatsByQuery"),
  getUserAvatarsFileStatsByMQuery: require("./getUserAvatarsFileStatsByMQuery"),
  getUserAvatarsFileByQuery: require("./getUserAvatarsFileByQuery"),
  getUserAvatarsFileByMQuery: require("./getUserAvatarsFileByMQuery"),
  updateUserAvatarsFileById: require("./updateUserAvatarsFileById"),
  updateUserAvatarsFileByIdList: require("./updateUserAvatarsFileByIdList"),
  updateUserAvatarsFileByQuery: require("./updateUserAvatarsFileByQuery"),
  updateUserAvatarsFileByMQuery: require("./updateUserAvatarsFileByMQuery"),
  deleteUserAvatarsFileById: require("./deleteUserAvatarsFileById"),
  deleteUserAvatarsFileByQuery: require("./deleteUserAvatarsFileByQuery"),
  deleteUserAvatarsFileByMQuery: require("./deleteUserAvatarsFileByMQuery"),
};
