module.exports = {
  createInviteAudit: require("./createInviteAudit"),
  createBulkInviteAudit: require("./createBulkInviteAudit"),
  getIdListOfInviteAuditByField: require("./getIdListOfInviteAuditByField"),
  getInviteAuditById: require("./getInviteAuditById"),
  getInviteAuditAggById: require("./getInviteAuditAggById"),
  getInviteAuditListByQuery: require("./getInviteAuditListByQuery"),
  getInviteAuditListByMQuery: require("./getInviteAuditListByMQuery"),
  getInviteAuditStatsByQuery: require("./getInviteAuditStatsByQuery"),
  getInviteAuditStatsByMQuery: require("./getInviteAuditStatsByMQuery"),
  getInviteAuditByQuery: require("./getInviteAuditByQuery"),
  getInviteAuditByMQuery: require("./getInviteAuditByMQuery"),
  updateInviteAuditById: require("./updateInviteAuditById"),
  updateInviteAuditByIdList: require("./updateInviteAuditByIdList"),
  updateInviteAuditByQuery: require("./updateInviteAuditByQuery"),
  updateInviteAuditByMQuery: require("./updateInviteAuditByMQuery"),
  deleteInviteAuditById: require("./deleteInviteAuditById"),
  deleteInviteAuditByQuery: require("./deleteInviteAuditByQuery"),
  deleteInviteAuditByMQuery: require("./deleteInviteAuditByMQuery"),
};
