module.exports = {
  createDishLine: require("./createDishLine"),
  createBulkDishLine: require("./createBulkDishLine"),
  getIdListOfDishLineByField: require("./getIdListOfDishLineByField"),
  getDishLineById: require("./getDishLineById"),
  getDishLineAggById: require("./getDishLineAggById"),
  getDishLineListByQuery: require("./getDishLineListByQuery"),
  getDishLineListByMQuery: require("./getDishLineListByMQuery"),
  getDishLineStatsByQuery: require("./getDishLineStatsByQuery"),
  getDishLineStatsByMQuery: require("./getDishLineStatsByMQuery"),
  getDishLineByQuery: require("./getDishLineByQuery"),
  getDishLineByMQuery: require("./getDishLineByMQuery"),
  updateDishLineById: require("./updateDishLineById"),
  updateDishLineByIdList: require("./updateDishLineByIdList"),
  updateDishLineByQuery: require("./updateDishLineByQuery"),
  updateDishLineByMQuery: require("./updateDishLineByMQuery"),
  deleteDishLineById: require("./deleteDishLineById"),
  deleteDishLineByQuery: require("./deleteDishLineByQuery"),
  deleteDishLineByMQuery: require("./deleteDishLineByMQuery"),
};
