FROM public.ecr.aws/docker/library/node:20-alpine AS build

WORKDIR /app

COPY package.json ./

RUN npm install --legacy-peer-deps --registry=https://registry.npmjs.org/

COPY . .
COPY .dev.env .dev.env

RUN npm run build

FROM nginx:alpine AS serve

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
