module.exports = {
  createAiGuidanceNote: require("./createAiGuidanceNote"),
  createBulkAiGuidanceNote: require("./createBulkAiGuidanceNote"),
  getIdListOfAiGuidanceNoteByField: require("./getIdListOfAiGuidanceNoteByField"),
  getAiGuidanceNoteById: require("./getAiGuidanceNoteById"),
  getAiGuidanceNoteAggById: require("./getAiGuidanceNoteAggById"),
  getAiGuidanceNoteListByQuery: require("./getAiGuidanceNoteListByQuery"),
  getAiGuidanceNoteListByMQuery: require("./getAiGuidanceNoteListByMQuery"),
  getAiGuidanceNoteStatsByQuery: require("./getAiGuidanceNoteStatsByQuery"),
  getAiGuidanceNoteStatsByMQuery: require("./getAiGuidanceNoteStatsByMQuery"),
  getAiGuidanceNoteByQuery: require("./getAiGuidanceNoteByQuery"),
  getAiGuidanceNoteByMQuery: require("./getAiGuidanceNoteByMQuery"),
  updateAiGuidanceNoteById: require("./updateAiGuidanceNoteById"),
  updateAiGuidanceNoteByIdList: require("./updateAiGuidanceNoteByIdList"),
  updateAiGuidanceNoteByQuery: require("./updateAiGuidanceNoteByQuery"),
  updateAiGuidanceNoteByMQuery: require("./updateAiGuidanceNoteByMQuery"),
  deleteAiGuidanceNoteById: require("./deleteAiGuidanceNoteById"),
  deleteAiGuidanceNoteByQuery: require("./deleteAiGuidanceNoteByQuery"),
  deleteAiGuidanceNoteByMQuery: require("./deleteAiGuidanceNoteByMQuery"),
};
