// Auto-generated by mindui sync pipeline.
// Routes here are AVAILABLE — pages exist for them.
// Other menu links should appear as "Coming Soon" until their service is generated.

export const AVAILABLE_ROUTES = new Set<string>([
  "/2fa",
  "/500",
  "/admin/bulk-import",
  "/admin/invites",
  "/admin/invites/:inviteLinkId",
  "/admin/invites/create",
  "/admin/suggestions",
  "/admin/users",
  "/admin/users/:userId",
  "/admin/users/create",
  "/ai-candidate-meals/:id/confirm",
  "/ai-chat",
  "/ai-guidance-notes/:id",
  "/ai-sessions",
  "/ai-sessions/:id",
  "/analytics/monthly",
  "/analytics/weekly",
  "/dashboard",
  "/dishes",
  "/dishes/:dishId",
  "/food-library",
  "/food-library/:foodItemId",
  "/forgot-password",
  "/invite-invalid",
  "/login",
  "/logout",
  "/maintenance",
  "/meals",
  "/meals/:id",
  "/meals/:id/edit",
  "/meals/log",
  "/preset-meals",
  "/preset-meals/:presetMealId",
  "/profile",
  "/register",
  "/reset-password",
  "/targets",
  "/verify-email",
  "/welcome",
]);

/**
 * Returns true if a route is currently available.
 * Matches dynamic segments — e.g. "/products/:id" is considered available
 * if "/products/:id" or its base "/products" is registered.
 */
export function isRouteAvailable(path: string): boolean {
  if (!path || path === "#") return false;
  if (AVAILABLE_ROUTES.has(path)) return true;
  // Strip trailing dynamic segments and try parents
  const segments = path.split("/").filter(Boolean);
  for (let i = segments.length - 1; i > 0; i--) {
    const partial = "/" + segments.slice(0, i).join("/");
    if (AVAILABLE_ROUTES.has(partial)) return true;
  }
  return false;
}
