module.exports = {
  createAiCandidateLine: require("./createAiCandidateLine"),
  createBulkAiCandidateLine: require("./createBulkAiCandidateLine"),
  getIdListOfAiCandidateLineByField: require("./getIdListOfAiCandidateLineByField"),
  getAiCandidateLineById: require("./getAiCandidateLineById"),
  getAiCandidateLineAggById: require("./getAiCandidateLineAggById"),
  getAiCandidateLineListByQuery: require("./getAiCandidateLineListByQuery"),
  getAiCandidateLineListByMQuery: require("./getAiCandidateLineListByMQuery"),
  getAiCandidateLineStatsByQuery: require("./getAiCandidateLineStatsByQuery"),
  getAiCandidateLineStatsByMQuery: require("./getAiCandidateLineStatsByMQuery"),
  getAiCandidateLineByQuery: require("./getAiCandidateLineByQuery"),
  getAiCandidateLineByMQuery: require("./getAiCandidateLineByMQuery"),
  updateAiCandidateLineById: require("./updateAiCandidateLineById"),
  updateAiCandidateLineByIdList: require("./updateAiCandidateLineByIdList"),
  updateAiCandidateLineByQuery: require("./updateAiCandidateLineByQuery"),
  updateAiCandidateLineByMQuery: require("./updateAiCandidateLineByMQuery"),
  deleteAiCandidateLineById: require("./deleteAiCandidateLineById"),
  deleteAiCandidateLineByQuery: require("./deleteAiCandidateLineByQuery"),
  deleteAiCandidateLineByMQuery: require("./deleteAiCandidateLineByMQuery"),
};
