module.exports = {
  createNutritionDay: require("./createNutritionDay"),
  createBulkNutritionDay: require("./createBulkNutritionDay"),
  getIdListOfNutritionDayByField: require("./getIdListOfNutritionDayByField"),
  getNutritionDayById: require("./getNutritionDayById"),
  getNutritionDayAggById: require("./getNutritionDayAggById"),
  getNutritionDayListByQuery: require("./getNutritionDayListByQuery"),
  getNutritionDayListByMQuery: require("./getNutritionDayListByMQuery"),
  getNutritionDayStatsByQuery: require("./getNutritionDayStatsByQuery"),
  getNutritionDayStatsByMQuery: require("./getNutritionDayStatsByMQuery"),
  getNutritionDayByQuery: require("./getNutritionDayByQuery"),
  getNutritionDayByMQuery: require("./getNutritionDayByMQuery"),
  updateNutritionDayById: require("./updateNutritionDayById"),
  updateNutritionDayByIdList: require("./updateNutritionDayByIdList"),
  updateNutritionDayByQuery: require("./updateNutritionDayByQuery"),
  updateNutritionDayByMQuery: require("./updateNutritionDayByMQuery"),
  deleteNutritionDayById: require("./deleteNutritionDayById"),
  deleteNutritionDayByQuery: require("./deleteNutritionDayByQuery"),
  deleteNutritionDayByMQuery: require("./deleteNutritionDayByMQuery"),
};
