module.exports = {
  createDish: require("./createDish"),
  createBulkDish: require("./createBulkDish"),
  getIdListOfDishByField: require("./getIdListOfDishByField"),
  getDishById: require("./getDishById"),
  getDishAggById: require("./getDishAggById"),
  getDishListByQuery: require("./getDishListByQuery"),
  getDishListByMQuery: require("./getDishListByMQuery"),
  getDishStatsByQuery: require("./getDishStatsByQuery"),
  getDishStatsByMQuery: require("./getDishStatsByMQuery"),
  getDishByQuery: require("./getDishByQuery"),
  getDishByMQuery: require("./getDishByMQuery"),
  updateDishById: require("./updateDishById"),
  updateDishByIdList: require("./updateDishByIdList"),
  updateDishByQuery: require("./updateDishByQuery"),
  updateDishByMQuery: require("./updateDishByMQuery"),
  deleteDishById: require("./deleteDishById"),
  deleteDishByQuery: require("./deleteDishByQuery"),
  deleteDishByMQuery: require("./deleteDishByMQuery"),
};
