FROM public.ecr.aws/docker/library/node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=test
ENV PORT=3000
ENV STATIC_FOLDER=/app/static
ENV DOC_TITLE="FitCheck Documentation"
ENV MOUNT_PATH=/document

EXPOSE 3000

CMD ["node", "server.js"]
