/**
 * FitCheck - Document Server
 *
 * A static file server for project documentation with full-text search.
 * Generated by Mindbricks Genesis.
 */

const express = require("express");
const path = require("path");
const fs = require("fs");
const FlexSearch = require("flexsearch");

const app = express();

// Configuration
const CONFIG = {
  port: process.env.PORT || 3000,
  staticFolder: process.env.STATIC_FOLDER || path.join(__dirname, "static"),
  title: process.env.DOC_TITLE || "FitCheck Documentation",
  // Mount path for when server is deployed behind a reverse proxy at a subpath (e.g., "/document")
  // Should NOT have trailing slash. Empty string means root.
  mountPath: (process.env.MOUNT_PATH || "").replace(/\/$/, ""),
};

// Initialize FlexSearch index
let searchIndex = null;
let searchDocuments = [];

function initializeSearch() {
  const searchIndexPath = path.join(CONFIG.staticFolder, "search-index.json");

  if (fs.existsSync(searchIndexPath)) {
    try {
      searchDocuments = JSON.parse(fs.readFileSync(searchIndexPath, "utf8"));

      // Create FlexSearch index
      searchIndex = new FlexSearch.Document({
        document: {
          id: "id",
          index: ["title", "content"],
          store: ["url", "title", "content"],
        },
        tokenize: "forward",
        resolution: 9,
      });

      // Add documents to index
      for (const doc of searchDocuments) {
        searchIndex.add(doc);
      }

      console.log(
        `Search index loaded with ${searchDocuments.length} documents`,
      );
    } catch (err) {
      console.error("Error loading search index:", err.message);
    }
  } else {
    console.log("No search index found at:", searchIndexPath);
  }
}

// Initialize search on startup
initializeSearch();

// Parse JSON bodies for API
app.use(express.json());

// Create a router for all documentation routes
const router = express.Router();

// Search API endpoint
router.get("/api/search", (req, res) => {
  const query = req.query.q;
  const limit = parseInt(req.query.limit) || 20;

  if (!query || query.trim().length < 2) {
    return res.json({ results: [], query: query || "" });
  }

  if (!searchIndex) {
    return res.status(503).json({ error: "Search index not available" });
  }

  try {
    // Search in both title and content fields
    const titleResults = searchIndex.search(query, {
      field: "title",
      limit: limit,
    });
    const contentResults = searchIndex.search(query, {
      field: "content",
      limit: limit,
    });

    // Merge and deduplicate results
    const seenIds = new Set();
    const results = [];

    // Process title matches first (higher priority)
    for (const result of titleResults) {
      for (const id of result.result) {
        if (!seenIds.has(id)) {
          seenIds.add(id);
          const doc = searchDocuments[id];
          if (doc) {
            results.push({
              url: doc.url,
              title: doc.title,
              snippet: getSnippet(doc.content, query),
              matchType: "title",
            });
          }
        }
      }
    }

    // Then content matches
    for (const result of contentResults) {
      for (const id of result.result) {
        if (!seenIds.has(id)) {
          seenIds.add(id);
          const doc = searchDocuments[id];
          if (doc) {
            results.push({
              url: doc.url,
              title: doc.title,
              snippet: getSnippet(doc.content, query),
              matchType: "content",
            });
          }
        }
      }
    }

    res.json({
      results: results.slice(0, limit),
      query: query,
      total: results.length,
    });
  } catch (err) {
    console.error("Search error:", err);
    res.status(500).json({ error: "Search failed" });
  }
});

// Get snippet with highlighted search term
function getSnippet(content, query, maxLength = 200) {
  if (!content) return "";

  const lowerContent = content.toLowerCase();
  const lowerQuery = query.toLowerCase();
  const index = lowerContent.indexOf(lowerQuery);

  let start, end;
  if (index === -1) {
    // Query not found, return beginning of content
    start = 0;
    end = Math.min(content.length, maxLength);
  } else {
    // Center the snippet around the match
    const padding = Math.floor((maxLength - query.length) / 2);
    start = Math.max(0, index - padding);
    end = Math.min(content.length, index + query.length + padding);
  }

  let snippet = content.substring(start, end);

  // Add ellipsis if truncated
  if (start > 0) snippet = "..." + snippet;
  if (end < content.length) snippet = snippet + "...";

  return snippet;
}

// Serve static HTML documentation
router.use(
  "/docs",
  express.static(path.join(CONFIG.staticFolder, "docs"), {
    extensions: ["html"],
    index: "index.html",
  }),
);

// Serve MD files for download
router.use(
  "/md",
  express.static(path.join(CONFIG.staticFolder, "md"), {
    setHeaders: (res, filePath) => {
      if (filePath.endsWith(".md")) {
        res.setHeader("Content-Type", "text/markdown; charset=utf-8");
        res.setHeader(
          "Content-Disposition",
          `attachment; filename="${path.basename(filePath)}"`,
        );
      }
    },
  }),
);

// Serve assets
router.use("/assets", express.static(path.join(CONFIG.staticFolder, "assets")));

// Serve llms.txt files for LLM consumption.
// At build time the files are generated with empty baseUrl ("").
// At runtime we inject CONFIG.mountPath so that all internal links include
// the correct prefix (e.g. /document/docs/intro.html) regardless of where
// the document server is mounted by the user.
function serveLlmsFile(fileName) {
  return (req, res) => {
    const filePath = path.join(CONFIG.staticFolder, fileName);
    if (!fs.existsSync(filePath)) {
      return res.status(404).send(`${fileName} not found`);
    }
    let content = fs.readFileSync(filePath, "utf-8");
    if (CONFIG.mountPath) {
      // Prefix absolute paths in markdown links: ](/docs/...) → ](/document/docs/...)
      // and ](/llms-full.txt) → ](/document/llms-full.txt)
      // Must run before the relative-path rule to avoid double-prefixing.
      content = content.replace(/\]\(\//g, `](${CONFIG.mountPath}/`);
      // Prefix relative paths in markdown links: ](docs/...) → ](/document/docs/...)
      // These come from introContent which uses relative links without leading /
      content = content.replace(/\]\(docs\//g, `](${CONFIG.mountPath}/docs/`);
      // Prefix plain-text path references: "Full documentation: /docs/intro.html"
      content = content.replace(/: \/docs\//g, `: ${CONFIG.mountPath}/docs/`);
      content = content.replace(/: docs\//g, `: ${CONFIG.mountPath}/docs/`);
    }
    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    res.send(content);
  };
}

router.get("/llms.txt", serveLlmsFile("llms.txt"));
router.get("/llms-full.txt", serveLlmsFile("llms-full.txt"));
router.get("/llms-restapi.txt", serveLlmsFile("llms-restapi.txt"));
router.get("/llms-prompts.txt", serveLlmsFile("llms-prompts.txt"));

// Root redirect to docs (uses CONFIG.mountPath for reverse proxy scenarios)
router.get("/", (req, res) => {
  res.redirect(`${CONFIG.mountPath}/docs/intro.html`);
});

// Docs root redirect
router.get("/docs", (req, res) => {
  res.redirect(`${CONFIG.mountPath}/docs/intro.html`);
});

// Handle URLs without .html extension
router.get("/docs/*", (req, res, next) => {
  // Remove mount path prefix if present to get the relative path
  let requestedPath = req.path;

  if (!requestedPath.endsWith(".html") && !requestedPath.includes(".")) {
    const htmlPath = path.join(CONFIG.staticFolder, requestedPath + ".html");
    if (fs.existsSync(htmlPath)) {
      return res.sendFile(htmlPath);
    }
  }

  next();
});

// 404 handler for router
router.use((req, res) => {
  res.status(404).send(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>404 - Not Found</title>
      <style>
        body { font-family: system-ui, sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; background: #f8fafc; }
        .container { text-align: center; }
        h1 { font-size: 4rem; margin: 0; color: #1e293b; }
        p { color: #64748b; margin: 16px 0; }
        a { color: #3b82f6; text-decoration: none; }
        a:hover { text-decoration: underline; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>404</h1>
        <p>The page you're looking for doesn't exist.</p>
        <a href="${CONFIG.mountPath}/docs/intro.html">Go to Documentation</a>
      </div>
    </body>
    </html>
  `);
});

// Always mount router at root - reverse proxy handles the /document prefix
// MOUNT_PATH is used for redirect URLs, not for Express mounting
app.use("/", router);

// Start server
app.listen(CONFIG.port, () => {
  console.log(
    `FitCheck Document Server running at http://localhost:${CONFIG.port}`,
  );
  console.log(`Serving static files from: ${CONFIG.staticFolder}`);
  if (CONFIG.mountPath) {
    console.log(`Mount path configured: ${CONFIG.mountPath}`);
    console.log(
      `Access documentation at: http://localhost:${CONFIG.port}${CONFIG.mountPath}/docs/intro.html`,
    );
  } else {
    console.log(`No mount path configured (serving at root)`);
    console.log(
      `Access documentation at: http://localhost:${CONFIG.port}/docs/intro.html`,
    );
  }
});

module.exports = app;
