module.exports = {
  createSys_toolCatalog: require("./createSys_toolCatalog"),
  createBulkSys_toolCatalog: require("./createBulkSys_toolCatalog"),
  getIdListOfSys_toolCatalogByField: require("./getIdListOfSys_toolCatalogByField"),
  getSys_toolCatalogById: require("./getSys_toolCatalogById"),
  getSys_toolCatalogAggById: require("./getSys_toolCatalogAggById"),
  getSys_toolCatalogListByQuery: require("./getSys_toolCatalogListByQuery"),
  getSys_toolCatalogListByMQuery: require("./getSys_toolCatalogListByMQuery"),
  getSys_toolCatalogStatsByQuery: require("./getSys_toolCatalogStatsByQuery"),
  getSys_toolCatalogStatsByMQuery: require("./getSys_toolCatalogStatsByMQuery"),
  getSys_toolCatalogByQuery: require("./getSys_toolCatalogByQuery"),
  getSys_toolCatalogByMQuery: require("./getSys_toolCatalogByMQuery"),
  updateSys_toolCatalogById: require("./updateSys_toolCatalogById"),
  updateSys_toolCatalogByIdList: require("./updateSys_toolCatalogByIdList"),
  updateSys_toolCatalogByQuery: require("./updateSys_toolCatalogByQuery"),
  updateSys_toolCatalogByMQuery: require("./updateSys_toolCatalogByMQuery"),
  deleteSys_toolCatalogById: require("./deleteSys_toolCatalogById"),
  deleteSys_toolCatalogByQuery: require("./deleteSys_toolCatalogByQuery"),
  deleteSys_toolCatalogByMQuery: require("./deleteSys_toolCatalogByMQuery"),
};
