module.exports = {
  createPresetLine: require("./createPresetLine"),
  createBulkPresetLine: require("./createBulkPresetLine"),
  getIdListOfPresetLineByField: require("./getIdListOfPresetLineByField"),
  getPresetLineById: require("./getPresetLineById"),
  getPresetLineAggById: require("./getPresetLineAggById"),
  getPresetLineListByQuery: require("./getPresetLineListByQuery"),
  getPresetLineListByMQuery: require("./getPresetLineListByMQuery"),
  getPresetLineStatsByQuery: require("./getPresetLineStatsByQuery"),
  getPresetLineStatsByMQuery: require("./getPresetLineStatsByMQuery"),
  getPresetLineByQuery: require("./getPresetLineByQuery"),
  getPresetLineByMQuery: require("./getPresetLineByMQuery"),
  updatePresetLineById: require("./updatePresetLineById"),
  updatePresetLineByIdList: require("./updatePresetLineByIdList"),
  updatePresetLineByQuery: require("./updatePresetLineByQuery"),
  updatePresetLineByMQuery: require("./updatePresetLineByMQuery"),
  deletePresetLineById: require("./deletePresetLineById"),
  deletePresetLineByQuery: require("./deletePresetLineByQuery"),
  deletePresetLineByMQuery: require("./deletePresetLineByMQuery"),
};
