const mealTrackerFunctions = require("./mealTracker");

module.exports = {
  // mealTracker Database
  createMealLog: mealTrackerFunctions.createMealLog,
  createBulkMealLog: mealTrackerFunctions.createBulkMealLog,
  getIdListOfMealLogByField: mealTrackerFunctions.getIdListOfMealLogByField,
  getMealLogById: mealTrackerFunctions.getMealLogById,
  getMealLogAggById: mealTrackerFunctions.getMealLogAggById,
  getMealLogListByQuery: mealTrackerFunctions.getMealLogListByQuery,
  getMealLogListByMQuery: mealTrackerFunctions.getMealLogListByMQuery,
  getMealLogStatsByQuery: mealTrackerFunctions.getMealLogStatsByQuery,
  getMealLogStatsByMQuery: mealTrackerFunctions.getMealLogStatsByMQuery,
  getMealLogByQuery: mealTrackerFunctions.getMealLogByQuery,
  getMealLogByMQuery: mealTrackerFunctions.getMealLogByMQuery,
  updateMealLogById: mealTrackerFunctions.updateMealLogById,
  updateMealLogByIdList: mealTrackerFunctions.updateMealLogByIdList,
  updateMealLogByQuery: mealTrackerFunctions.updateMealLogByQuery,
  updateMealLogByMQuery: mealTrackerFunctions.updateMealLogByMQuery,
  deleteMealLogById: mealTrackerFunctions.deleteMealLogById,
  deleteMealLogByQuery: mealTrackerFunctions.deleteMealLogByQuery,
  deleteMealLogByMQuery: mealTrackerFunctions.deleteMealLogByMQuery,
  dbScriptCreateMeallog: mealTrackerFunctions.dbScriptCreateMeallog,
  dbScriptGetMeallog: mealTrackerFunctions.dbScriptGetMeallog,
  dbScriptListMeallogs: mealTrackerFunctions.dbScriptListMeallogs,
  dbScriptUpdateMeallog: mealTrackerFunctions.dbScriptUpdateMeallog,
  dbScriptDeleteMeallog: mealTrackerFunctions.dbScriptDeleteMeallog,
  dbScript_fetchListmeallog: mealTrackerFunctions.dbScript_fetchListmeallog,
  createMealLine: mealTrackerFunctions.createMealLine,
  createBulkMealLine: mealTrackerFunctions.createBulkMealLine,
  getIdListOfMealLineByField: mealTrackerFunctions.getIdListOfMealLineByField,
  getMealLineById: mealTrackerFunctions.getMealLineById,
  getMealLineAggById: mealTrackerFunctions.getMealLineAggById,
  getMealLineListByQuery: mealTrackerFunctions.getMealLineListByQuery,
  getMealLineListByMQuery: mealTrackerFunctions.getMealLineListByMQuery,
  getMealLineStatsByQuery: mealTrackerFunctions.getMealLineStatsByQuery,
  getMealLineStatsByMQuery: mealTrackerFunctions.getMealLineStatsByMQuery,
  getMealLineByQuery: mealTrackerFunctions.getMealLineByQuery,
  getMealLineByMQuery: mealTrackerFunctions.getMealLineByMQuery,
  updateMealLineById: mealTrackerFunctions.updateMealLineById,
  updateMealLineByIdList: mealTrackerFunctions.updateMealLineByIdList,
  updateMealLineByQuery: mealTrackerFunctions.updateMealLineByQuery,
  updateMealLineByMQuery: mealTrackerFunctions.updateMealLineByMQuery,
  deleteMealLineById: mealTrackerFunctions.deleteMealLineById,
  deleteMealLineByQuery: mealTrackerFunctions.deleteMealLineByQuery,
  deleteMealLineByMQuery: mealTrackerFunctions.deleteMealLineByMQuery,
  dbScriptCreateMealline: mealTrackerFunctions.dbScriptCreateMealline,
  dbScriptUpdateMealline: mealTrackerFunctions.dbScriptUpdateMealline,
  dbScriptDeleteMealline: mealTrackerFunctions.dbScriptDeleteMealline,
  dbScriptListMeallines: mealTrackerFunctions.dbScriptListMeallines,
  dbScript_fetchListmealline: mealTrackerFunctions.dbScript_fetchListmealline,
  createNutritionDay: mealTrackerFunctions.createNutritionDay,
  createBulkNutritionDay: mealTrackerFunctions.createBulkNutritionDay,
  getIdListOfNutritionDayByField:
    mealTrackerFunctions.getIdListOfNutritionDayByField,
  getNutritionDayById: mealTrackerFunctions.getNutritionDayById,
  getNutritionDayAggById: mealTrackerFunctions.getNutritionDayAggById,
  getNutritionDayListByQuery: mealTrackerFunctions.getNutritionDayListByQuery,
  getNutritionDayListByMQuery: mealTrackerFunctions.getNutritionDayListByMQuery,
  getNutritionDayStatsByQuery: mealTrackerFunctions.getNutritionDayStatsByQuery,
  getNutritionDayStatsByMQuery:
    mealTrackerFunctions.getNutritionDayStatsByMQuery,
  getNutritionDayByQuery: mealTrackerFunctions.getNutritionDayByQuery,
  getNutritionDayByMQuery: mealTrackerFunctions.getNutritionDayByMQuery,
  updateNutritionDayById: mealTrackerFunctions.updateNutritionDayById,
  updateNutritionDayByIdList: mealTrackerFunctions.updateNutritionDayByIdList,
  updateNutritionDayByQuery: mealTrackerFunctions.updateNutritionDayByQuery,
  updateNutritionDayByMQuery: mealTrackerFunctions.updateNutritionDayByMQuery,
  deleteNutritionDayById: mealTrackerFunctions.deleteNutritionDayById,
  deleteNutritionDayByQuery: mealTrackerFunctions.deleteNutritionDayByQuery,
  deleteNutritionDayByMQuery: mealTrackerFunctions.deleteNutritionDayByMQuery,
  dbScriptGetDailyprogress: mealTrackerFunctions.dbScriptGetDailyprogress,
  dbScriptGetNutritionday: mealTrackerFunctions.dbScriptGetNutritionday,
  dbScriptListNutritiondays: mealTrackerFunctions.dbScriptListNutritiondays,
  dbScriptGetWeeklyanalytics: mealTrackerFunctions.dbScriptGetWeeklyanalytics,
  dbScriptGetMonthlyanalytics: mealTrackerFunctions.dbScriptGetMonthlyanalytics,
  dbScriptTriggerDailyremindercheck:
    mealTrackerFunctions.dbScriptTriggerDailyremindercheck,
  dbScriptTriggerDailysummary: mealTrackerFunctions.dbScriptTriggerDailysummary,
  dbScript_fetchListnutritionday:
    mealTrackerFunctions.dbScript_fetchListnutritionday,
};
