module.exports = {
  createAiCandidateMeal: require("./createAiCandidateMeal"),
  createBulkAiCandidateMeal: require("./createBulkAiCandidateMeal"),
  getIdListOfAiCandidateMealByField: require("./getIdListOfAiCandidateMealByField"),
  getAiCandidateMealById: require("./getAiCandidateMealById"),
  getAiCandidateMealAggById: require("./getAiCandidateMealAggById"),
  getAiCandidateMealListByQuery: require("./getAiCandidateMealListByQuery"),
  getAiCandidateMealListByMQuery: require("./getAiCandidateMealListByMQuery"),
  getAiCandidateMealStatsByQuery: require("./getAiCandidateMealStatsByQuery"),
  getAiCandidateMealStatsByMQuery: require("./getAiCandidateMealStatsByMQuery"),
  getAiCandidateMealByQuery: require("./getAiCandidateMealByQuery"),
  getAiCandidateMealByMQuery: require("./getAiCandidateMealByMQuery"),
  updateAiCandidateMealById: require("./updateAiCandidateMealById"),
  updateAiCandidateMealByIdList: require("./updateAiCandidateMealByIdList"),
  updateAiCandidateMealByQuery: require("./updateAiCandidateMealByQuery"),
  updateAiCandidateMealByMQuery: require("./updateAiCandidateMealByMQuery"),
  deleteAiCandidateMealById: require("./deleteAiCandidateMealById"),
  deleteAiCandidateMealByQuery: require("./deleteAiCandidateMealByQuery"),
  deleteAiCandidateMealByMQuery: require("./deleteAiCandidateMealByMQuery"),
};
