module.exports = {
  createPresetMeal: require("./createPresetMeal"),
  createBulkPresetMeal: require("./createBulkPresetMeal"),
  getIdListOfPresetMealByField: require("./getIdListOfPresetMealByField"),
  getPresetMealById: require("./getPresetMealById"),
  getPresetMealAggById: require("./getPresetMealAggById"),
  getPresetMealListByQuery: require("./getPresetMealListByQuery"),
  getPresetMealListByMQuery: require("./getPresetMealListByMQuery"),
  getPresetMealStatsByQuery: require("./getPresetMealStatsByQuery"),
  getPresetMealStatsByMQuery: require("./getPresetMealStatsByMQuery"),
  getPresetMealByQuery: require("./getPresetMealByQuery"),
  getPresetMealByMQuery: require("./getPresetMealByMQuery"),
  updatePresetMealById: require("./updatePresetMealById"),
  updatePresetMealByIdList: require("./updatePresetMealByIdList"),
  updatePresetMealByQuery: require("./updatePresetMealByQuery"),
  updatePresetMealByMQuery: require("./updatePresetMealByMQuery"),
  deletePresetMealById: require("./deletePresetMealById"),
  deletePresetMealByQuery: require("./deletePresetMealByQuery"),
  deletePresetMealByMQuery: require("./deletePresetMealByMQuery"),
};
