module.exports = {
  createAiSession: require("./createAiSession"),
  createBulkAiSession: require("./createBulkAiSession"),
  getIdListOfAiSessionByField: require("./getIdListOfAiSessionByField"),
  getAiSessionById: require("./getAiSessionById"),
  getAiSessionAggById: require("./getAiSessionAggById"),
  getAiSessionListByQuery: require("./getAiSessionListByQuery"),
  getAiSessionListByMQuery: require("./getAiSessionListByMQuery"),
  getAiSessionStatsByQuery: require("./getAiSessionStatsByQuery"),
  getAiSessionStatsByMQuery: require("./getAiSessionStatsByMQuery"),
  getAiSessionByQuery: require("./getAiSessionByQuery"),
  getAiSessionByMQuery: require("./getAiSessionByMQuery"),
  updateAiSessionById: require("./updateAiSessionById"),
  updateAiSessionByIdList: require("./updateAiSessionByIdList"),
  updateAiSessionByQuery: require("./updateAiSessionByQuery"),
  updateAiSessionByMQuery: require("./updateAiSessionByMQuery"),
  deleteAiSessionById: require("./deleteAiSessionById"),
  deleteAiSessionByQuery: require("./deleteAiSessionByQuery"),
  deleteAiSessionByMQuery: require("./deleteAiSessionByMQuery"),
};
