const mainFunctions = require("./main");

module.exports = {
  // main Database
  createUser: mainFunctions.createUser,
  createBulkUser: mainFunctions.createBulkUser,
  getIdListOfUserByField: mainFunctions.getIdListOfUserByField,
  getUserById: mainFunctions.getUserById,
  getUserAggById: mainFunctions.getUserAggById,
  getUserListByQuery: mainFunctions.getUserListByQuery,
  getUserListByMQuery: mainFunctions.getUserListByMQuery,
  getUserStatsByQuery: mainFunctions.getUserStatsByQuery,
  getUserStatsByMQuery: mainFunctions.getUserStatsByMQuery,
  getUserByQuery: mainFunctions.getUserByQuery,
  getUserByMQuery: mainFunctions.getUserByMQuery,
  updateUserById: mainFunctions.updateUserById,
  updateUserByIdList: mainFunctions.updateUserByIdList,
  updateUserByQuery: mainFunctions.updateUserByQuery,
  updateUserByMQuery: mainFunctions.updateUserByMQuery,
  deleteUserById: mainFunctions.deleteUserById,
  deleteUserByQuery: mainFunctions.deleteUserByQuery,
  deleteUserByMQuery: mainFunctions.deleteUserByMQuery,
  getUserByEmail: mainFunctions.getUserByEmail,
  getCachedUserById: mainFunctions.getCachedUserById,
  dbScriptGetUser: mainFunctions.dbScriptGetUser,
  dbScriptUpdateUser: mainFunctions.dbScriptUpdateUser,
  dbScriptUpdateProfile: mainFunctions.dbScriptUpdateProfile,
  dbScriptCreateUser: mainFunctions.dbScriptCreateUser,
  dbScriptDeleteUser: mainFunctions.dbScriptDeleteUser,
  dbScriptArchiveProfile: mainFunctions.dbScriptArchiveProfile,
  dbScriptListUsers: mainFunctions.dbScriptListUsers,
  dbScriptSearchUsers: mainFunctions.dbScriptSearchUsers,
  dbScriptUpdateUserrole: mainFunctions.dbScriptUpdateUserrole,
  dbScriptUpdateUserpassword: mainFunctions.dbScriptUpdateUserpassword,
  dbScriptUpdateUserpasswordbyadmin:
    mainFunctions.dbScriptUpdateUserpasswordbyadmin,
  dbScriptGetBriefuser: mainFunctions.dbScriptGetBriefuser,
  dbScriptStreamTest: mainFunctions.dbScriptStreamTest,
  createUserAvatarsFile: mainFunctions.createUserAvatarsFile,
  createBulkUserAvatarsFile: mainFunctions.createBulkUserAvatarsFile,
  getIdListOfUserAvatarsFileByField:
    mainFunctions.getIdListOfUserAvatarsFileByField,
  getUserAvatarsFileById: mainFunctions.getUserAvatarsFileById,
  getUserAvatarsFileAggById: mainFunctions.getUserAvatarsFileAggById,
  getUserAvatarsFileListByQuery: mainFunctions.getUserAvatarsFileListByQuery,
  getUserAvatarsFileListByMQuery: mainFunctions.getUserAvatarsFileListByMQuery,
  getUserAvatarsFileStatsByQuery: mainFunctions.getUserAvatarsFileStatsByQuery,
  getUserAvatarsFileStatsByMQuery:
    mainFunctions.getUserAvatarsFileStatsByMQuery,
  getUserAvatarsFileByQuery: mainFunctions.getUserAvatarsFileByQuery,
  getUserAvatarsFileByMQuery: mainFunctions.getUserAvatarsFileByMQuery,
  updateUserAvatarsFileById: mainFunctions.updateUserAvatarsFileById,
  updateUserAvatarsFileByIdList: mainFunctions.updateUserAvatarsFileByIdList,
  updateUserAvatarsFileByQuery: mainFunctions.updateUserAvatarsFileByQuery,
  updateUserAvatarsFileByMQuery: mainFunctions.updateUserAvatarsFileByMQuery,
  deleteUserAvatarsFileById: mainFunctions.deleteUserAvatarsFileById,
  deleteUserAvatarsFileByQuery: mainFunctions.deleteUserAvatarsFileByQuery,
  deleteUserAvatarsFileByMQuery: mainFunctions.deleteUserAvatarsFileByMQuery,
  dbScriptGetUseravatarsfile: mainFunctions.dbScriptGetUseravatarsfile,
  dbScriptListUseravatarsfiles: mainFunctions.dbScriptListUseravatarsfiles,
  dbScriptDeleteUseravatarsfile: mainFunctions.dbScriptDeleteUseravatarsfile,
  dbScript_fetchListuseravatarsfile:
    mainFunctions.dbScript_fetchListuseravatarsfile,
};
