module.exports = {
  createSys_agentOverride: require("./createSys_agentOverride"),
  createBulkSys_agentOverride: require("./createBulkSys_agentOverride"),
  getIdListOfSys_agentOverrideByField: require("./getIdListOfSys_agentOverrideByField"),
  getSys_agentOverrideById: require("./getSys_agentOverrideById"),
  getSys_agentOverrideAggById: require("./getSys_agentOverrideAggById"),
  getSys_agentOverrideListByQuery: require("./getSys_agentOverrideListByQuery"),
  getSys_agentOverrideListByMQuery: require("./getSys_agentOverrideListByMQuery"),
  getSys_agentOverrideStatsByQuery: require("./getSys_agentOverrideStatsByQuery"),
  getSys_agentOverrideStatsByMQuery: require("./getSys_agentOverrideStatsByMQuery"),
  getSys_agentOverrideByQuery: require("./getSys_agentOverrideByQuery"),
  getSys_agentOverrideByMQuery: require("./getSys_agentOverrideByMQuery"),
  updateSys_agentOverrideById: require("./updateSys_agentOverrideById"),
  updateSys_agentOverrideByIdList: require("./updateSys_agentOverrideByIdList"),
  updateSys_agentOverrideByQuery: require("./updateSys_agentOverrideByQuery"),
  updateSys_agentOverrideByMQuery: require("./updateSys_agentOverrideByMQuery"),
  deleteSys_agentOverrideById: require("./deleteSys_agentOverrideById"),
  deleteSys_agentOverrideByQuery: require("./deleteSys_agentOverrideByQuery"),
  deleteSys_agentOverrideByMQuery: require("./deleteSys_agentOverrideByMQuery"),
};
