module.exports = {
  createMacroTarget: require("./createMacroTarget"),
  createBulkMacroTarget: require("./createBulkMacroTarget"),
  getIdListOfMacroTargetByField: require("./getIdListOfMacroTargetByField"),
  getMacroTargetById: require("./getMacroTargetById"),
  getMacroTargetAggById: require("./getMacroTargetAggById"),
  getMacroTargetListByQuery: require("./getMacroTargetListByQuery"),
  getMacroTargetListByMQuery: require("./getMacroTargetListByMQuery"),
  getMacroTargetStatsByQuery: require("./getMacroTargetStatsByQuery"),
  getMacroTargetStatsByMQuery: require("./getMacroTargetStatsByMQuery"),
  getMacroTargetByQuery: require("./getMacroTargetByQuery"),
  getMacroTargetByMQuery: require("./getMacroTargetByMQuery"),
  updateMacroTargetById: require("./updateMacroTargetById"),
  updateMacroTargetByIdList: require("./updateMacroTargetByIdList"),
  updateMacroTargetByQuery: require("./updateMacroTargetByQuery"),
  updateMacroTargetByMQuery: require("./updateMacroTargetByMQuery"),
  deleteMacroTargetById: require("./deleteMacroTargetById"),
  deleteMacroTargetByQuery: require("./deleteMacroTargetByQuery"),
  deleteMacroTargetByMQuery: require("./deleteMacroTargetByMQuery"),
};
