module.exports = {
  createUser: require("./createUser"),
  createBulkUser: require("./createBulkUser"),
  getIdListOfUserByField: require("./getIdListOfUserByField"),
  getUserById: require("./getUserById"),
  getUserAggById: require("./getUserAggById"),
  getUserListByQuery: require("./getUserListByQuery"),
  getUserListByMQuery: require("./getUserListByMQuery"),
  getUserStatsByQuery: require("./getUserStatsByQuery"),
  getUserStatsByMQuery: require("./getUserStatsByMQuery"),
  getUserByQuery: require("./getUserByQuery"),
  getUserByMQuery: require("./getUserByMQuery"),
  updateUserById: require("./updateUserById"),
  updateUserByIdList: require("./updateUserByIdList"),
  updateUserByQuery: require("./updateUserByQuery"),
  updateUserByMQuery: require("./updateUserByMQuery"),
  deleteUserById: require("./deleteUserById"),
  deleteUserByQuery: require("./deleteUserByQuery"),
  deleteUserByMQuery: require("./deleteUserByMQuery"),
  getUserByEmail: require("./getUserByEmail"),
  getCachedUserById: require("./getCachedUserById"),
};
