FROM public.ecr.aws/docker/library/node:20-alpine AS build

WORKDIR /app

COPY package.json ./

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --no-frozen-lockfile

COPY . .
COPY .env.stage .env.stage

RUN pnpm run build-stage

FROM nginx:alpine AS serve

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
