const inviteLinkFunctions = require("./inviteLink");
const inviteAuditFunctions = require("./inviteAudit");

module.exports = {
  // invitationcenter Database
  createInviteLink: inviteLinkFunctions.createInviteLink,
  createBulkInviteLink: inviteLinkFunctions.createBulkInviteLink,
  getIdListOfInviteLinkByField:
    inviteLinkFunctions.getIdListOfInviteLinkByField,
  getInviteLinkById: inviteLinkFunctions.getInviteLinkById,
  getInviteLinkAggById: inviteLinkFunctions.getInviteLinkAggById,
  getInviteLinkListByQuery: inviteLinkFunctions.getInviteLinkListByQuery,
  getInviteLinkListByMQuery: inviteLinkFunctions.getInviteLinkListByMQuery,
  getInviteLinkStatsByQuery: inviteLinkFunctions.getInviteLinkStatsByQuery,
  getInviteLinkStatsByMQuery: inviteLinkFunctions.getInviteLinkStatsByMQuery,
  getInviteLinkByQuery: inviteLinkFunctions.getInviteLinkByQuery,
  getInviteLinkByMQuery: inviteLinkFunctions.getInviteLinkByMQuery,
  updateInviteLinkById: inviteLinkFunctions.updateInviteLinkById,
  updateInviteLinkByIdList: inviteLinkFunctions.updateInviteLinkByIdList,
  updateInviteLinkByQuery: inviteLinkFunctions.updateInviteLinkByQuery,
  updateInviteLinkByMQuery: inviteLinkFunctions.updateInviteLinkByMQuery,
  deleteInviteLinkById: inviteLinkFunctions.deleteInviteLinkById,
  deleteInviteLinkByQuery: inviteLinkFunctions.deleteInviteLinkByQuery,
  deleteInviteLinkByMQuery: inviteLinkFunctions.deleteInviteLinkByMQuery,
  getInviteLinkByInviteCode: inviteLinkFunctions.getInviteLinkByInviteCode,
  dbScriptCreateInvitelink: inviteLinkFunctions.dbScriptCreateInvitelink,
  dbScriptActivateInvitelink: inviteLinkFunctions.dbScriptActivateInvitelink,
  dbScriptRevokeInvitelink: inviteLinkFunctions.dbScriptRevokeInvitelink,
  dbScriptDeliverInviteemail: inviteLinkFunctions.dbScriptDeliverInviteemail,
  dbScriptValidateInvitecode: inviteLinkFunctions.dbScriptValidateInvitecode,
  dbScriptConsumeInvitelink: inviteLinkFunctions.dbScriptConsumeInvitelink,
  dbScriptGetInvitelinkbycode: inviteLinkFunctions.dbScriptGetInvitelinkbycode,
  dbScriptGetInvitelink: inviteLinkFunctions.dbScriptGetInvitelink,
  dbScriptListInvitelinks: inviteLinkFunctions.dbScriptListInvitelinks,
  dbScript_fetchListinvitelink:
    inviteLinkFunctions.dbScript_fetchListinvitelink,
  createInviteAudit: inviteAuditFunctions.createInviteAudit,
  createBulkInviteAudit: inviteAuditFunctions.createBulkInviteAudit,
  getIdListOfInviteAuditByField:
    inviteAuditFunctions.getIdListOfInviteAuditByField,
  getInviteAuditById: inviteAuditFunctions.getInviteAuditById,
  getInviteAuditAggById: inviteAuditFunctions.getInviteAuditAggById,
  getInviteAuditListByQuery: inviteAuditFunctions.getInviteAuditListByQuery,
  getInviteAuditListByMQuery: inviteAuditFunctions.getInviteAuditListByMQuery,
  getInviteAuditStatsByQuery: inviteAuditFunctions.getInviteAuditStatsByQuery,
  getInviteAuditStatsByMQuery: inviteAuditFunctions.getInviteAuditStatsByMQuery,
  getInviteAuditByQuery: inviteAuditFunctions.getInviteAuditByQuery,
  getInviteAuditByMQuery: inviteAuditFunctions.getInviteAuditByMQuery,
  updateInviteAuditById: inviteAuditFunctions.updateInviteAuditById,
  updateInviteAuditByIdList: inviteAuditFunctions.updateInviteAuditByIdList,
  updateInviteAuditByQuery: inviteAuditFunctions.updateInviteAuditByQuery,
  updateInviteAuditByMQuery: inviteAuditFunctions.updateInviteAuditByMQuery,
  deleteInviteAuditById: inviteAuditFunctions.deleteInviteAuditById,
  deleteInviteAuditByQuery: inviteAuditFunctions.deleteInviteAuditByQuery,
  deleteInviteAuditByMQuery: inviteAuditFunctions.deleteInviteAuditByMQuery,
  dbScriptListInviteaudits: inviteAuditFunctions.dbScriptListInviteaudits,
  dbScript_fetchListinviteaudit:
    inviteAuditFunctions.dbScript_fetchListinviteaudit,
};
