import { useEffect, useMemo, useRef, useState } from "react";
import {
  ExternalLink,
  Maximize2,
  Minimize2,
  RefreshCw,
  X,
  Save,
} from "lucide-react";
import { useChatStore } from "../../stores/chatStore";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import DataViewActionCard from "./DataViewActionCard";
import QrCodeActionCard from "./QrCodeActionCard";

/**
 * Visual Browser Component
 *
 * Renders standalone content generated by AI/frontend tools:
 * html, markdown, json, data views, qr/secret cards, and map views.
 * Also supports local save/load of browser view config.
 */
export default function HtmlViewer() {
  const {
    htmlContent,
    setHtmlContent,
    sendMessageStream,
    browserView,
    setBrowserView,
    clearBrowserView,
  } = useChatStore();
  const iframeRef = useRef(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [savedViews, setSavedViews] = useState([]);
  const [selectedSavedView, setSelectedSavedView] = useState("");

  const activeView = useMemo(() => {
    if (browserView) return browserView;
    if (htmlContent) {
      return {
        type: "html",
        title: "Generated View",
        html: htmlContent,
      };
    }
    return null;
  }, [browserView, htmlContent]);

  useEffect(() => {
    const raw = localStorage.getItem("chat-browser-saved-views");
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) setSavedViews(parsed);
    } catch {
      // Ignore malformed local cache.
    }
  }, []);

  const persistSavedViews = (views) => {
    setSavedViews(views);
    localStorage.setItem("chat-browser-saved-views", JSON.stringify(views));
  };

  const handleSaveCurrentView = () => {
    if (!activeView) return;
    const title = window.prompt(
      "Save current view as:",
      activeView.title || "Saved View",
    );
    if (!title) return;
    const next = [
      ...savedViews.filter((v) => v.name !== title),
      { name: title, view: activeView, savedAt: new Date().toISOString() },
    ];
    persistSavedViews(next);
    setSelectedSavedView(title);
  };

  const handleLoadSavedView = (name) => {
    setSelectedSavedView(name);
    const item = savedViews.find((v) => v.name === name);
    if (item?.view) {
      setBrowserView(item.view);
      if (item.view.type === "html") {
        setHtmlContent(item.view.html || null);
      }
    }
  };

  // Inject the HTML into the iframe
  useEffect(() => {
    if (iframeRef.current && activeView?.type === "html" && activeView?.html) {
      const iframe = iframeRef.current;
      const doc = iframe.contentDocument || iframe.contentWindow.document;

      // Create the HTML with injected styles and link handler
      const wrappedHtml = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
            * { box-sizing: border-box; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              line-height: 1.6;
              color: #1f2937;
              padding: 16px;
              margin: 0;
              background: #ffffff;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 16px 0;
            }
            th, td {
              padding: 12px;
              text-align: left;
              border-bottom: 1px solid #e5e7eb;
            }
            th {
              background: #f9fafb;
              font-weight: 600;
            }
            tr:hover {
              background: #f3f4f6;
            }
            a {
              color: #2563eb;
              text-decoration: none;
              cursor: pointer;
            }
            a:hover {
              text-decoration: underline;
            }
            .btn {
              display: inline-block;
              padding: 8px 16px;
              background: #2563eb;
              color: white;
              border-radius: 6px;
              text-decoration: none;
              margin: 4px;
            }
            .btn:hover {
              background: #1d4ed8;
              text-decoration: none;
            }
            .btn-danger {
              background: #dc2626;
            }
            .btn-danger:hover {
              background: #b91c1c;
            }
            .card {
              border: 1px solid #e5e7eb;
              border-radius: 8px;
              padding: 16px;
              margin: 8px 0;
            }
            .badge {
              display: inline-block;
              padding: 2px 8px;
              border-radius: 9999px;
              font-size: 12px;
              font-weight: 500;
            }
            .badge-success { background: #d1fae5; color: #065f46; }
            .badge-warning { background: #fef3c7; color: #92400e; }
            .badge-danger { background: #fee2e2; color: #991b1b; }
            .badge-info { background: #dbeafe; color: #1e40af; }
            img {
              max-width: 100%;
              height: auto;
            }
            h1, h2, h3, h4 { margin: 16px 0 8px 0; }
            h1 { font-size: 24px; }
            h2 { font-size: 20px; }
            h3 { font-size: 18px; }
            .empty-state {
              text-align: center;
              padding: 40px;
              color: #6b7280;
            }
          </style>
        </head>
        <body>
          ${activeView.html}
          <script>
            // Intercept link clicks
            document.addEventListener('click', function(e) {
              const link = e.target.closest('a');
              if (link) {
                e.preventDefault();
                const href = link.getAttribute('href');
                const action = link.getAttribute('data-action');
                const query = link.getAttribute('data-query');
                
                // Send message to parent
                window.parent.postMessage({
                  type: 'link-click',
                  href: href,
                  action: action,
                  query: query || link.textContent
                }, '*');
              }
            });
          </script>
        </body>
        </html>
      `;

      doc.open();
      doc.write(wrappedHtml);
      doc.close();
    }
  }, [activeView]);

  // Handle messages from iframe
  useEffect(() => {
    const handleMessage = (event) => {
      if (event.data?.type === "link-click") {
        const { query, action, href } = event.data;

        // Generate a query based on the link
        let aiQuery = query;
        if (action) {
          aiQuery = action;
        } else if (href && href !== "#") {
          aiQuery = `Show me details for: ${href}`;
        }

        // Send the query to the AI
        if (aiQuery) {
          sendMessageStream(aiQuery);
        }
      }
    };

    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, [sendMessageStream]);

  if (!activeView) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center p-6">
        <div className="w-16 h-16 bg-gray-100 dark:bg-gray-800 rounded-full flex items-center justify-center mb-4">
          <ExternalLink className="w-8 h-8 text-gray-400" />
        </div>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
          No Content Yet
        </h3>
        <p className="text-gray-600 dark:text-gray-400 text-sm max-w-xs">
          Ask the AI to generate a page or view, like "Show me a list of users"
          or "Create a dashboard for orders"
        </p>
      </div>
    );
  }

  return (
    <div
      className={`flex flex-col h-full ${isFullscreen ? "fixed inset-0 z-50 bg-white dark:bg-gray-900" : ""}`}
    >
      {/* Toolbar */}
      <div className="flex items-center justify-between p-2 border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800">
        <div className="min-w-0">
          <span className="text-sm font-medium text-gray-700 dark:text-gray-300 truncate block">
            {activeView.title || "Visual Browser"}
          </span>
        </div>
        <div className="flex items-center gap-1 flex-wrap justify-end">
          <button
            onClick={handleSaveCurrentView}
            className="p-1.5 rounded hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            title="Save current view"
          >
            <Save className="w-4 h-4 text-gray-600 dark:text-gray-400" />
          </button>
          {savedViews.length > 0 && (
            <select
              value={selectedSavedView}
              onChange={(e) => handleLoadSavedView(e.target.value)}
              className="text-xs border border-gray-300 dark:border-gray-600 rounded px-2 py-1 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300"
              title="Load saved view"
            >
              <option value="">Load saved view...</option>
              {savedViews.map((view) => (
                <option key={view.name} value={view.name}>
                  {view.name}
                </option>
              ))}
            </select>
          )}
          <button
            onClick={() => {
              if (iframeRef.current) {
                const doc = iframeRef.current.contentDocument;
                doc.location.reload();
              }
            }}
            className="p-1.5 rounded hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            title="Refresh"
            disabled={activeView.type !== "html"}
          >
            <RefreshCw className="w-4 h-4 text-gray-600 dark:text-gray-400" />
          </button>
          <button
            onClick={() => setIsFullscreen(!isFullscreen)}
            className="p-1.5 rounded hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            title={isFullscreen ? "Exit Fullscreen" : "Fullscreen"}
          >
            {isFullscreen ? (
              <Minimize2 className="w-4 h-4 text-gray-600 dark:text-gray-400" />
            ) : (
              <Maximize2 className="w-4 h-4 text-gray-600 dark:text-gray-400" />
            )}
          </button>
          <button
            onClick={() => {
              setHtmlContent(null);
              clearBrowserView();
            }}
            className="p-1.5 rounded hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            title="Close"
          >
            <X className="w-4 h-4 text-gray-600 dark:text-gray-400" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-hidden bg-white dark:bg-gray-900">
        {activeView.type === "html" && (
          <iframe
            ref={iframeRef}
            className="w-full h-full border-0 bg-white"
            sandbox="allow-scripts allow-same-origin"
            title="Generated HTML Content"
          />
        )}

        {activeView.type === "json" && (
          <div className="p-3 h-full overflow-auto">
            <pre className="text-xs bg-gray-100 dark:bg-gray-800 rounded-lg p-3 overflow-auto whitespace-pre-wrap break-all">
              {JSON.stringify(activeView.data ?? {}, null, 2)}
            </pre>
          </div>
        )}

        {activeView.type === "markdown" && (
          <div className="p-4 h-full overflow-auto prose prose-sm dark:prose-invert max-w-none">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {activeView.markdown || ""}
            </ReactMarkdown>
          </div>
        )}

        {activeView.type === "dataView" && (
          <div className="p-3 h-full overflow-auto">
            <DataViewActionCard action={activeView.action || activeView} />
          </div>
        )}

        {activeView.type === "qrcode" && (
          <div className="p-3 h-full overflow-auto">
            <QrCodeActionCard action={activeView.action || activeView} />
          </div>
        )}

        {activeView.type === "secret" && (
          <div className="p-3 h-full overflow-auto">
            <div className="text-sm text-gray-500">
              Secret preview is not available in this project.
            </div>
          </div>
        )}

        {activeView.type === "map" && (
          <div className="p-3 h-full overflow-auto">
            <div className="text-sm text-gray-500">
              Map view is not available because GeoPoint support is disabled.
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
