const express = require("express");
const app = express();
const routes = require("routes");
const cors = require("cors");
const { getDomain } = require("tldts");
const cookieParser = require("cookie-parser");

const { errorConverter, errorHandler } = require("middlewares/error");

const apiFace = require("./api-face");

const CORS_CONTROL_ACTIVE = process.env.CORS_CONTROL_ACTIVE === "true";
const corsOrigins = process.env.ALLOWED_ORIGINS ?? "";
const allowAllSubdomains = process.env.ALLOW_SUBDOMAINS === "true";

const parseOrigins = (str) =>
  (str || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

const envOrigins = new Set(parseOrigins(corsOrigins));

const sameBaseDomain = (origin) => {
  try {
    const serviceUrl = process.env.SERVICE_URL;
    const { hostname, protocol } = new URL(serviceUrl);
    const { hostname: oHost, protocol: oProto } = new URL(origin);
    if (protocol !== oProto) return false;
    const base = getDomain(hostname);
    const apiBase = getDomain(oHost);
    return base && apiBase && base === apiBase;
  } catch {
    return false;
  }
};

// Dev localhost range (Vite default ports)
for (let p = 5170; p <= 5190; p++) {
  envOrigins.add(`http://localhost:${p}`);
  envOrigins.add(`http://127.0.0.1:${p}`);
  envOrigins.add(`https://localhost:${p}`);
  envOrigins.add(`https://127.0.0.1:${p}`);
}

const allowed = [...envOrigins];

const exposedHeaders = ["lrmwufitcheck-access-token"];

const corsOptions = {
  origin(origin, cb) {
    if (!CORS_CONTROL_ACTIVE) return cb(null, true);

    // allow server-to-server, curl, Postman (no Origin header)
    if (!origin) return cb(null, true);

    // quick exact-match allowlist
    if (allowed.includes(origin)) return cb(null, true);

    const subdomainOK = allowAllSubdomains && sameBaseDomain(origin);
    if (subdomainOK) return cb(null, true);

    return cb(new Error(`CORS blocked for origin: ${origin}`));
  },
  credentials: true,
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: [
    "Content-Type",
    "Authorization",
    "X-Requested-With",
    "Accept",
    "lrmwufitcheck-access-token",
  ],
  exposedHeaders,
  optionsSuccessStatus: 204,
};

app.set("trust proxy", true); // important if behind a proxy/CDN for secure cookies

app.use(cors(corsOptions));
app.options("*", cors(corsOptions));

app.use(cookieParser());

app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ extended: true, limit: "10mb" }));

app.get("/health", (req, res) => {
  res.setHeader("Content-Type", "application/json");
  res.status(200).send({
    serviceName: process.env.SERVICE_NAME,
    projectVersion: process.env.PROJECT_VERSION,
    serviceVersion: process.env.SERVICE_VERSION,
    notice: "This service is generated by MindBricks",
  });
});

// v1 api routes
app.use("/", routes);

// Api Documentation
apiFace(app);

app.use(errorConverter);

app.use(errorHandler);

module.exports = app;
