/**
 * Chat Routes
 *
 * Handles AI chat interactions, routing user messages to appropriate MCP tools.
 * Supports both regular HTTP and SSE streaming responses.
 */

const express = require("express");
const router = express.Router();
const chatService = require("../services/chat-service");
const aiService = require("../services/ai-service");
const conversationStore = require("../services/conversation-store");
const uuidAliasRegistry = require("../services/uuid-alias-registry");
const {
  VISUALIZATION_TOOLS,
  TOOL_HANDLERS,
  VISUALIZATION_TOOL_NAMES,
} = require("../services/visualization-tools");
const { v4: uuidv4 } = require("uuid");
const logger = require("../common/logger");
const { filterTools } = require("../common/tool-filters");

/**
 * Enhanced MCP Manager wrapper that includes BFF-level tools:
 *  - search_mindbricks_docs  (documentation search)
 *  - showQrCode, showBusinessApiListInFrontEnd, showBusinessApiGalleryInFrontEnd,
 *    showBusinessApiMapInFrontEnd  (data visualization, backed by cross-service api-docs)
 */
class EnhancedMcpManager {
  constructor(mcpManager) {
    this.mcpManager = mcpManager;
  }

  getAllTools() {
    const mcpTools = this.mcpManager.getAllTools();
    return [...mcpTools, aiService.DOCS_SEARCH_TOOL, ...VISUALIZATION_TOOLS];
  }

  async callTool(toolName, args, userContext) {
    if (toolName === "search_mindbricks_docs") {
      return aiService.searchDocumentation(args.query, args.limit);
    }
    if (VISUALIZATION_TOOL_NAMES.has(toolName)) {
      const handler = TOOL_HANDLERS[toolName];
      return handler(args);
    }
    return this.mcpManager.callTool(toolName, args, userContext);
  }

  getConnectionStatus() {
    return this.mcpManager.getConnectionStatus();
  }
}

/**
 * POST /api/chat
 *
 * Send a chat message and get AI response with tool calls.
 *
 * Body:
 * - message: string - User's message
 * - conversationId?: string - Optional conversation ID for context
 * - context?: object - Additional context data
 */
router.post("/", async (req, res) => {
  try {
    const {
      message,
      conversationId,
      context = {},
      disabledServices,
    } = req.body;
    const mcpManager = req.app.get("mcpManager");

    if (!message || typeof message !== "string") {
      return res.status(400).json({ error: "Message is required" });
    }

    // Build user context with access token for MCP tool authentication
    const userContext = {
      userId: req.user.userId,
      email: req.user.email,
      fullname: req.user.fullname,
      roleId: req.user.roleId,
      sessionId: req.user.sessionId,
      accessToken: req.accessToken, // Forward the user's token to MCP tools
      ...context,
    };

    // Process the chat message
    const response = await chatService.processMessage(
      mcpManager,
      message,
      userContext,
      conversationId,
      { disabledServices: disabledServices || [] },
    );

    res.json(response);
  } catch (error) {
    logger.error("Chat error:", error);
    res.status(500).json({
      error: "Failed to process chat message",
      details: error.message,
    });
  }
});

/**
 * POST /api/chat/stream
 *
 * Stream a chat response using Server-Sent Events (SSE).
 * Returns real-time tokens as they're generated by the AI.
 *
 * Body:
 * - message: string - User's message
 * - conversationId?: string - Optional conversation ID for context
 */
router.post("/stream", async (req, res) => {
  const { message, conversationId, disabledServices } = req.body;
  const mcpManager = req.app.get("mcpManager");

  if (!message || typeof message !== "string") {
    return res.status(400).json({ error: "Message is required" });
  }

  // Set SSE headers
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");
  res.flushHeaders();

  const convId = conversationId || uuidv4();
  const startTime = Date.now();

  // Build user context
  const userContext = {
    userId: req.user.userId,
    email: req.user.email,
    fullname: req.user.fullname,
    roleId: req.user.roleId,
    sessionId: req.user.sessionId,
    accessToken: req.accessToken,
    conversationId: convId,
  };

  // Helper to send SSE events with flush for real-time delivery
  const sendEvent = (event, data) => {
    res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
    // Flush the response to ensure immediate delivery
    if (res.flush) {
      res.flush();
    }
  };

  try {
    // Check if AI is available
    if (!aiService.isAvailable()) {
      sendEvent("error", {
        message:
          "AI service not configured. Please configure OPENAI_API_KEY or ANTHROPIC_API_KEY in environment variables",
      });
      sendEvent("done", { conversationId: convId });
      res.end();
      return;
    }

    // Wrap MCP manager with documentation search capability
    const enhancedManager = new EnhancedMcpManager(mcpManager);

    // Filter MCP tools, then re-add BFF-level tools (always kept)
    const mcpTools = mcpManager.getAllTools();
    const { tools: filteredMcpTools } = filterTools(mcpTools, {
      disabledServices: disabledServices || [],
    });
    const availableTools = [
      ...filteredMcpTools,
      aiService.DOCS_SEARCH_TOOL,
      ...VISUALIZATION_TOOLS,
    ];
    const history =
      (await conversationStore.getMessages(convId, req.user.userId)) || [];

    // Build messages
    const messages = [
      ...history.map((m) => ({ role: m.role, content: m.content })),
      { role: "user", content: message },
    ];

    // Store user message
    await conversationStore.addMessage(
      convId,
      {
        role: "user",
        content: message,
        timestamp: new Date().toISOString(),
      },
      req.user.userId,
    );

    // Send start event
    sendEvent("start", {
      conversationId: convId,
      provider: aiService.getActiveProvider(),
      aliasMapSummary: aiService.UUID_ALIAS_ENABLED
        ? {
            enabled: true,
            ...uuidAliasRegistry.getAliasMapSummary(userContext),
          }
        : { enabled: false, count: 0, samples: [] },
    });

    // Stream the response - build segments to preserve inline order
    let segments = [];
    let currentTextContent = "";
    let toolCalls = [];

    let aliasMapSummary = aiService.UUID_ALIAS_ENABLED
      ? { enabled: true, ...uuidAliasRegistry.getAliasMapSummary(userContext) }
      : { enabled: false, count: 0, samples: [] };
    for await (const event of aiService.streamChat(
      messages,
      availableTools,
      enhancedManager,
      userContext,
    )) {
      switch (event.type) {
        case "text":
          currentTextContent += event.content;
          sendEvent("text", { content: event.content });
          break;
        case "tool_start":
          // Flush any accumulated text before the tool call
          if (currentTextContent.trim()) {
            segments.push({ type: "text", content: currentTextContent });
            currentTextContent = "";
          }
          sendEvent("tool_start", { tool: event.tool });
          break;
        case "tool_executing":
          sendEvent("tool_executing", { tool: event.tool, args: event.args });
          break;
        case "tool_result":
          // Add tool segment with full details
          segments.push({
            type: "tool",
            tool: event.tool,
            args: event.args,
            result: event.result,
            error: event.error,
            success: event.success,
            status: "complete",
          });
          toolCalls.push({
            tool: event.tool,
            args: event.args,
            result: event.result,
            error: event.error,
          });
          sendEvent("tool_result", {
            tool: event.tool,
            result: event.result,
            error: event.error,
            success: event.success,
          });
          break;
        case "done":
          // Flush any remaining text
          if (currentTextContent.trim()) {
            segments.push({ type: "text", content: currentTextContent });
          }
          aliasMapSummary = event.aliasMapSummary || aliasMapSummary;
          break;
      }
    }

    // Build full content for backward compatibility
    const fullContent = segments
      .filter((s) => s.type === "text")
      .map((s) => s.content)
      .join("");

    // Store assistant response with segments for proper ordering
    await conversationStore.addMessage(
      convId,
      {
        role: "assistant",
        content: fullContent,
        segments: segments,
        toolCalls: toolCalls,
        timestamp: new Date().toISOString(),
      },
      req.user.userId,
    );

    // Send completion event
    sendEvent("done", {
      conversationId: convId,
      toolCalls: toolCalls,
      processingTime: Date.now() - startTime,
      aliasMapSummary,
    });

    res.end();
  } catch (error) {
    logger.error("Stream chat error:", error);
    sendEvent("error", { message: error.message });
    res.end();
  }
});

/**
 * POST /api/chat/tool
 *
 * Directly call an MCP tool (for advanced users/debugging).
 *
 * Body:
 * - tool: string - Tool name
 * - args: object - Tool arguments
 */
router.post("/tool", async (req, res) => {
  try {
    const { tool, args = {} } = req.body;
    const mcpManager = req.app.get("mcpManager");

    if (!tool) {
      return res.status(400).json({ error: "Tool name is required" });
    }

    const userContext = {
      userId: req.user.userId,
      sessionId: req.user.sessionId,
      accessToken: req.accessToken, // Forward the user's token to MCP tools
    };

    const result = await mcpManager.callTool(tool, args, userContext);
    res.json(result);
  } catch (error) {
    logger.error("Tool call error:", error);
    res.status(500).json({
      error: "Failed to call tool",
      details: error.message,
    });
  }
});

/**
 * GET /api/chat/conversations
 *
 * List all conversations for the current user.
 */
router.get("/conversations", async (req, res) => {
  try {
    const { page = 1, limit = 20 } = req.query;
    const offset = (parseInt(page) - 1) * parseInt(limit);
    const conversations = await conversationStore.listConversations(
      req.user?.userId || "anonymous",
      parseInt(limit),
      offset,
    );
    res.json(conversations);
  } catch (error) {
    logger.error("List conversations error:", error);
    res.status(500).json({ error: "Failed to list conversations" });
  }
});

/**
 * GET /api/chat/conversations/search
 *
 * Search conversations by content.
 * NOTE: This must come BEFORE /conversations/:conversationId
 */
router.get("/conversations/search", async (req, res) => {
  try {
    const { q, limit = 20 } = req.query;

    if (!q || typeof q !== "string") {
      return res.status(400).json({ error: "Search query (q) is required" });
    }

    const results = await conversationStore.searchConversations(
      req.user?.userId || "anonymous",
      q,
      parseInt(limit),
    );
    res.json({ results });
  } catch (error) {
    logger.error("Search conversations error:", error);
    res.status(500).json({ error: "Failed to search conversations" });
  }
});

/**
 * GET /api/chat/conversations/health
 *
 * Check Elasticsearch health.
 * NOTE: This must come BEFORE /conversations/:conversationId
 */
router.get("/conversations/health", async (req, res) => {
  try {
    const health = await conversationStore.healthCheck();
    res.json(health);
  } catch (error) {
    logger.error("Health check error:", error);
    res.status(500).json({ error: "Health check failed" });
  }
});

/**
 * GET /api/chat/conversations/:conversationId
 *
 * Get a specific conversation with messages.
 */
router.get("/conversations/:conversationId", async (req, res) => {
  try {
    const { conversationId } = req.params;
    const userId = req.user?.userId || "anonymous";
    const conversation = await conversationStore.getConversation(
      conversationId,
      userId,
    );

    if (!conversation) {
      return res.status(404).json({ error: "Conversation not found" });
    }

    res.json(conversation);
  } catch (error) {
    logger.error("Get conversation error:", error);
    res.status(500).json({ error: "Failed to get conversation" });
  }
});

/**
 * PATCH /api/chat/conversations/:conversationId
 *
 * Update conversation (e.g., title).
 */
router.patch("/conversations/:conversationId", async (req, res) => {
  try {
    const { conversationId } = req.params;
    const userId = req.user?.userId || "anonymous";
    const { title } = req.body;

    if (title !== undefined) {
      await conversationStore.updateTitle(conversationId, title, userId);
    }

    res.json({ success: true });
  } catch (error) {
    logger.error("Update conversation error:", error);
    res.status(500).json({ error: "Failed to update conversation" });
  }
});

/**
 * DELETE /api/chat/conversations/:conversationId
 *
 * Delete a conversation.
 */
router.delete("/conversations/:conversationId", async (req, res) => {
  try {
    const { conversationId } = req.params;
    const userId = req.user?.userId || "anonymous";
    await conversationStore.clearConversation(conversationId, userId);
    uuidAliasRegistry.clearConversationMap(conversationId);
    res.json({ success: true });
  } catch (error) {
    logger.error("Delete conversation error:", error);
    res.status(500).json({ error: "Failed to delete conversation" });
  }
});

/**
 * GET /api/chat/history/:conversationId
 *
 * Get conversation history (legacy endpoint).
 */
router.get("/history/:conversationId", async (req, res) => {
  try {
    const { conversationId } = req.params;
    const history = await chatService.getConversationHistory(
      conversationId,
      req.user.userId,
    );
    res.json({ conversationId, history });
  } catch (error) {
    logger.error("History retrieval error:", error);
    res.status(500).json({ error: "Failed to get conversation history" });
  }
});

/**
 * DELETE /api/chat/history/:conversationId
 *
 * Clear conversation history.
 */
router.delete("/history/:conversationId", async (req, res) => {
  try {
    const { conversationId } = req.params;
    await chatService.clearConversationHistory(conversationId, req.user.userId);
    uuidAliasRegistry.clearConversationMap(conversationId);
    res.json({ success: true, message: "Conversation cleared" });
  } catch (error) {
    logger.error("History clear error:", error);
    res.status(500).json({ error: "Failed to clear conversation history" });
  }
});

/**
 * GET /api/chat/status
 *
 * Get AI service status and configuration.
 */
router.get("/status", async (req, res) => {
  try {
    const status = chatService.getAIStatus();
    const mcpManager = req.app.get("mcpManager");
    const enhancedManager = new EnhancedMcpManager(mcpManager);

    res.json({
      ai: status,
      tools: {
        count: enhancedManager.getAllTools().length,
        mcpTools: mcpManager.getAllTools().length,
        builtInTools: 1 + VISUALIZATION_TOOLS.length, // docs search + visualization
        connections: mcpManager.getConnectionStatus(),
      },
      features: {
        documentationSearch: true,
        streaming: true,
        conversationHistory: true,
        uuidAliasMapping: aiService.UUID_ALIAS_ENABLED,
      },
      aliasRegistry: aiService.UUID_ALIAS_ENABLED
        ? uuidAliasRegistry.getRegistryStats()
        : {
            activeConversations: 0,
            totalAliases: 0,
            maxConversations: 0,
            ttlMs: 0,
          },
    });
  } catch (error) {
    logger.error("Status error:", error);
    res.status(500).json({ error: "Failed to get status" });
  }
});

module.exports = router;
