const macroTargetFunctions = require("./macroTarget");
const foodItemFunctions = require("./foodItem");
const presetMealFunctions = require("./presetMeal");
const presetLineFunctions = require("./presetLine");
const dishFunctions = require("./dish");
const dishLineFunctions = require("./dishLine");

module.exports = {
  // nutritionlibrary Database
  createMacroTarget: macroTargetFunctions.createMacroTarget,
  createBulkMacroTarget: macroTargetFunctions.createBulkMacroTarget,
  getIdListOfMacroTargetByField:
    macroTargetFunctions.getIdListOfMacroTargetByField,
  getMacroTargetById: macroTargetFunctions.getMacroTargetById,
  getMacroTargetAggById: macroTargetFunctions.getMacroTargetAggById,
  getMacroTargetListByQuery: macroTargetFunctions.getMacroTargetListByQuery,
  getMacroTargetListByMQuery: macroTargetFunctions.getMacroTargetListByMQuery,
  getMacroTargetStatsByQuery: macroTargetFunctions.getMacroTargetStatsByQuery,
  getMacroTargetStatsByMQuery: macroTargetFunctions.getMacroTargetStatsByMQuery,
  getMacroTargetByQuery: macroTargetFunctions.getMacroTargetByQuery,
  getMacroTargetByMQuery: macroTargetFunctions.getMacroTargetByMQuery,
  updateMacroTargetById: macroTargetFunctions.updateMacroTargetById,
  updateMacroTargetByIdList: macroTargetFunctions.updateMacroTargetByIdList,
  updateMacroTargetByQuery: macroTargetFunctions.updateMacroTargetByQuery,
  updateMacroTargetByMQuery: macroTargetFunctions.updateMacroTargetByMQuery,
  deleteMacroTargetById: macroTargetFunctions.deleteMacroTargetById,
  deleteMacroTargetByQuery: macroTargetFunctions.deleteMacroTargetByQuery,
  deleteMacroTargetByMQuery: macroTargetFunctions.deleteMacroTargetByMQuery,
  dbScriptSetMacrotarget: macroTargetFunctions.dbScriptSetMacrotarget,
  dbScriptGetMymacrotarget: macroTargetFunctions.dbScriptGetMymacrotarget,
  dbScriptGetMymacrotargetforlogging:
    macroTargetFunctions.dbScriptGetMymacrotargetforlogging,
  dbScript_fetchListmacrotarget:
    macroTargetFunctions.dbScript_fetchListmacrotarget,
  createFoodItem: foodItemFunctions.createFoodItem,
  createBulkFoodItem: foodItemFunctions.createBulkFoodItem,
  getIdListOfFoodItemByField: foodItemFunctions.getIdListOfFoodItemByField,
  getFoodItemById: foodItemFunctions.getFoodItemById,
  getFoodItemAggById: foodItemFunctions.getFoodItemAggById,
  getFoodItemListByQuery: foodItemFunctions.getFoodItemListByQuery,
  getFoodItemListByMQuery: foodItemFunctions.getFoodItemListByMQuery,
  getFoodItemStatsByQuery: foodItemFunctions.getFoodItemStatsByQuery,
  getFoodItemStatsByMQuery: foodItemFunctions.getFoodItemStatsByMQuery,
  getFoodItemByQuery: foodItemFunctions.getFoodItemByQuery,
  getFoodItemByMQuery: foodItemFunctions.getFoodItemByMQuery,
  updateFoodItemById: foodItemFunctions.updateFoodItemById,
  updateFoodItemByIdList: foodItemFunctions.updateFoodItemByIdList,
  updateFoodItemByQuery: foodItemFunctions.updateFoodItemByQuery,
  updateFoodItemByMQuery: foodItemFunctions.updateFoodItemByMQuery,
  deleteFoodItemById: foodItemFunctions.deleteFoodItemById,
  deleteFoodItemByQuery: foodItemFunctions.deleteFoodItemByQuery,
  deleteFoodItemByMQuery: foodItemFunctions.deleteFoodItemByMQuery,
  dbScriptCreateFooditem: foodItemFunctions.dbScriptCreateFooditem,
  dbScriptGetFooditem: foodItemFunctions.dbScriptGetFooditem,
  dbScriptListFooditems: foodItemFunctions.dbScriptListFooditems,
  dbScriptUpdateFooditem: foodItemFunctions.dbScriptUpdateFooditem,
  dbScriptDeleteFooditem: foodItemFunctions.dbScriptDeleteFooditem,
  dbScriptGetFooditemforlogging:
    foodItemFunctions.dbScriptGetFooditemforlogging,
  dbScript_fetchListfooditem: foodItemFunctions.dbScript_fetchListfooditem,
  createPresetMeal: presetMealFunctions.createPresetMeal,
  createBulkPresetMeal: presetMealFunctions.createBulkPresetMeal,
  getIdListOfPresetMealByField:
    presetMealFunctions.getIdListOfPresetMealByField,
  getPresetMealById: presetMealFunctions.getPresetMealById,
  getPresetMealAggById: presetMealFunctions.getPresetMealAggById,
  getPresetMealListByQuery: presetMealFunctions.getPresetMealListByQuery,
  getPresetMealListByMQuery: presetMealFunctions.getPresetMealListByMQuery,
  getPresetMealStatsByQuery: presetMealFunctions.getPresetMealStatsByQuery,
  getPresetMealStatsByMQuery: presetMealFunctions.getPresetMealStatsByMQuery,
  getPresetMealByQuery: presetMealFunctions.getPresetMealByQuery,
  getPresetMealByMQuery: presetMealFunctions.getPresetMealByMQuery,
  updatePresetMealById: presetMealFunctions.updatePresetMealById,
  updatePresetMealByIdList: presetMealFunctions.updatePresetMealByIdList,
  updatePresetMealByQuery: presetMealFunctions.updatePresetMealByQuery,
  updatePresetMealByMQuery: presetMealFunctions.updatePresetMealByMQuery,
  deletePresetMealById: presetMealFunctions.deletePresetMealById,
  deletePresetMealByQuery: presetMealFunctions.deletePresetMealByQuery,
  deletePresetMealByMQuery: presetMealFunctions.deletePresetMealByMQuery,
  dbScriptCreatePresetmeal: presetMealFunctions.dbScriptCreatePresetmeal,
  dbScriptGetPresetmeal: presetMealFunctions.dbScriptGetPresetmeal,
  dbScriptListPresetmeals: presetMealFunctions.dbScriptListPresetmeals,
  dbScriptUpdatePresetmeal: presetMealFunctions.dbScriptUpdatePresetmeal,
  dbScriptDeletePresetmeal: presetMealFunctions.dbScriptDeletePresetmeal,
  dbScriptGetPresetmealforlogging:
    presetMealFunctions.dbScriptGetPresetmealforlogging,
  dbScript_fetchListpresetmeal:
    presetMealFunctions.dbScript_fetchListpresetmeal,
  createPresetLine: presetLineFunctions.createPresetLine,
  createBulkPresetLine: presetLineFunctions.createBulkPresetLine,
  getIdListOfPresetLineByField:
    presetLineFunctions.getIdListOfPresetLineByField,
  getPresetLineById: presetLineFunctions.getPresetLineById,
  getPresetLineAggById: presetLineFunctions.getPresetLineAggById,
  getPresetLineListByQuery: presetLineFunctions.getPresetLineListByQuery,
  getPresetLineListByMQuery: presetLineFunctions.getPresetLineListByMQuery,
  getPresetLineStatsByQuery: presetLineFunctions.getPresetLineStatsByQuery,
  getPresetLineStatsByMQuery: presetLineFunctions.getPresetLineStatsByMQuery,
  getPresetLineByQuery: presetLineFunctions.getPresetLineByQuery,
  getPresetLineByMQuery: presetLineFunctions.getPresetLineByMQuery,
  updatePresetLineById: presetLineFunctions.updatePresetLineById,
  updatePresetLineByIdList: presetLineFunctions.updatePresetLineByIdList,
  updatePresetLineByQuery: presetLineFunctions.updatePresetLineByQuery,
  updatePresetLineByMQuery: presetLineFunctions.updatePresetLineByMQuery,
  deletePresetLineById: presetLineFunctions.deletePresetLineById,
  deletePresetLineByQuery: presetLineFunctions.deletePresetLineByQuery,
  deletePresetLineByMQuery: presetLineFunctions.deletePresetLineByMQuery,
  dbScriptAddPresetline: presetLineFunctions.dbScriptAddPresetline,
  dbScriptListPresetlines: presetLineFunctions.dbScriptListPresetlines,
  dbScriptDeletePresetline: presetLineFunctions.dbScriptDeletePresetline,
  dbScript_fetchListpresetline:
    presetLineFunctions.dbScript_fetchListpresetline,
  createDish: dishFunctions.createDish,
  createBulkDish: dishFunctions.createBulkDish,
  getIdListOfDishByField: dishFunctions.getIdListOfDishByField,
  getDishById: dishFunctions.getDishById,
  getDishAggById: dishFunctions.getDishAggById,
  getDishListByQuery: dishFunctions.getDishListByQuery,
  getDishListByMQuery: dishFunctions.getDishListByMQuery,
  getDishStatsByQuery: dishFunctions.getDishStatsByQuery,
  getDishStatsByMQuery: dishFunctions.getDishStatsByMQuery,
  getDishByQuery: dishFunctions.getDishByQuery,
  getDishByMQuery: dishFunctions.getDishByMQuery,
  updateDishById: dishFunctions.updateDishById,
  updateDishByIdList: dishFunctions.updateDishByIdList,
  updateDishByQuery: dishFunctions.updateDishByQuery,
  updateDishByMQuery: dishFunctions.updateDishByMQuery,
  deleteDishById: dishFunctions.deleteDishById,
  deleteDishByQuery: dishFunctions.deleteDishByQuery,
  deleteDishByMQuery: dishFunctions.deleteDishByMQuery,
  dbScriptCreateDish: dishFunctions.dbScriptCreateDish,
  dbScriptGetDish: dishFunctions.dbScriptGetDish,
  dbScriptListDishes: dishFunctions.dbScriptListDishes,
  dbScriptUpdateDish: dishFunctions.dbScriptUpdateDish,
  dbScriptDeleteDish: dishFunctions.dbScriptDeleteDish,
  dbScript_fetchListdish: dishFunctions.dbScript_fetchListdish,
  createDishLine: dishLineFunctions.createDishLine,
  createBulkDishLine: dishLineFunctions.createBulkDishLine,
  getIdListOfDishLineByField: dishLineFunctions.getIdListOfDishLineByField,
  getDishLineById: dishLineFunctions.getDishLineById,
  getDishLineAggById: dishLineFunctions.getDishLineAggById,
  getDishLineListByQuery: dishLineFunctions.getDishLineListByQuery,
  getDishLineListByMQuery: dishLineFunctions.getDishLineListByMQuery,
  getDishLineStatsByQuery: dishLineFunctions.getDishLineStatsByQuery,
  getDishLineStatsByMQuery: dishLineFunctions.getDishLineStatsByMQuery,
  getDishLineByQuery: dishLineFunctions.getDishLineByQuery,
  getDishLineByMQuery: dishLineFunctions.getDishLineByMQuery,
  updateDishLineById: dishLineFunctions.updateDishLineById,
  updateDishLineByIdList: dishLineFunctions.updateDishLineByIdList,
  updateDishLineByQuery: dishLineFunctions.updateDishLineByQuery,
  updateDishLineByMQuery: dishLineFunctions.updateDishLineByMQuery,
  deleteDishLineById: dishLineFunctions.deleteDishLineById,
  deleteDishLineByQuery: dishLineFunctions.deleteDishLineByQuery,
  deleteDishLineByMQuery: dishLineFunctions.deleteDishLineByMQuery,
  dbScriptAddDishline: dishLineFunctions.dbScriptAddDishline,
  dbScriptListDishlines: dishLineFunctions.dbScriptListDishlines,
  dbScriptDeleteDishline: dishLineFunctions.dbScriptDeleteDishline,
  dbScript_fetchListdishline: dishLineFunctions.dbScript_fetchListdishline,
};
