module.exports = {
  createSys_agentConversation: require("./createSys_agentConversation"),
  createBulkSys_agentConversation: require("./createBulkSys_agentConversation"),
  getIdListOfSys_agentConversationByField: require("./getIdListOfSys_agentConversationByField"),
  getSys_agentConversationById: require("./getSys_agentConversationById"),
  getSys_agentConversationAggById: require("./getSys_agentConversationAggById"),
  getSys_agentConversationListByQuery: require("./getSys_agentConversationListByQuery"),
  getSys_agentConversationListByMQuery: require("./getSys_agentConversationListByMQuery"),
  getSys_agentConversationStatsByQuery: require("./getSys_agentConversationStatsByQuery"),
  getSys_agentConversationStatsByMQuery: require("./getSys_agentConversationStatsByMQuery"),
  getSys_agentConversationByQuery: require("./getSys_agentConversationByQuery"),
  getSys_agentConversationByMQuery: require("./getSys_agentConversationByMQuery"),
  updateSys_agentConversationById: require("./updateSys_agentConversationById"),
  updateSys_agentConversationByIdList: require("./updateSys_agentConversationByIdList"),
  updateSys_agentConversationByQuery: require("./updateSys_agentConversationByQuery"),
  updateSys_agentConversationByMQuery: require("./updateSys_agentConversationByMQuery"),
  deleteSys_agentConversationById: require("./deleteSys_agentConversationById"),
  deleteSys_agentConversationByQuery: require("./deleteSys_agentConversationByQuery"),
  deleteSys_agentConversationByMQuery: require("./deleteSys_agentConversationByMQuery"),
};
