const utils = require("./utils");
const dbApiScripts = require("./dbApiScripts");

module.exports = {
  createUser: utils.createUser,
  createBulkUser: utils.createBulkUser,
  getIdListOfUserByField: utils.getIdListOfUserByField,
  getUserById: utils.getUserById,
  getUserAggById: utils.getUserAggById,
  getUserListByQuery: utils.getUserListByQuery,
  getUserListByMQuery: utils.getUserListByMQuery,
  getUserStatsByQuery: utils.getUserStatsByQuery,
  getUserStatsByMQuery: utils.getUserStatsByMQuery,
  getUserByQuery: utils.getUserByQuery,
  getUserByMQuery: utils.getUserByMQuery,
  updateUserById: utils.updateUserById,
  updateUserByIdList: utils.updateUserByIdList,
  updateUserByQuery: utils.updateUserByQuery,
  updateUserByMQuery: utils.updateUserByMQuery,
  deleteUserById: utils.deleteUserById,
  deleteUserByQuery: utils.deleteUserByQuery,
  deleteUserByMQuery: utils.deleteUserByMQuery,
  getUserByEmail: utils.getUserByEmail,
  getCachedUserById: utils.getCachedUserById,
  dbScriptGetUser: dbApiScripts.dbScriptGetUser,
  dbScriptUpdateUser: dbApiScripts.dbScriptUpdateUser,
  dbScriptUpdateProfile: dbApiScripts.dbScriptUpdateProfile,
  dbScriptCreateUser: dbApiScripts.dbScriptCreateUser,
  dbScriptDeleteUser: dbApiScripts.dbScriptDeleteUser,
  dbScriptArchiveProfile: dbApiScripts.dbScriptArchiveProfile,
  dbScriptListUsers: dbApiScripts.dbScriptListUsers,
  dbScriptSearchUsers: dbApiScripts.dbScriptSearchUsers,
  dbScriptUpdateUserrole: dbApiScripts.dbScriptUpdateUserrole,
  dbScriptUpdateUserpassword: dbApiScripts.dbScriptUpdateUserpassword,
  dbScriptUpdateUserpasswordbyadmin:
    dbApiScripts.dbScriptUpdateUserpasswordbyadmin,
  dbScriptGetBriefuser: dbApiScripts.dbScriptGetBriefuser,
  dbScriptStreamTest: dbApiScripts.dbScriptStreamTest,
};
