module.exports = {
  createSys_agentExecution: require("./createSys_agentExecution"),
  createBulkSys_agentExecution: require("./createBulkSys_agentExecution"),
  getIdListOfSys_agentExecutionByField: require("./getIdListOfSys_agentExecutionByField"),
  getSys_agentExecutionById: require("./getSys_agentExecutionById"),
  getSys_agentExecutionAggById: require("./getSys_agentExecutionAggById"),
  getSys_agentExecutionListByQuery: require("./getSys_agentExecutionListByQuery"),
  getSys_agentExecutionListByMQuery: require("./getSys_agentExecutionListByMQuery"),
  getSys_agentExecutionStatsByQuery: require("./getSys_agentExecutionStatsByQuery"),
  getSys_agentExecutionStatsByMQuery: require("./getSys_agentExecutionStatsByMQuery"),
  getSys_agentExecutionByQuery: require("./getSys_agentExecutionByQuery"),
  getSys_agentExecutionByMQuery: require("./getSys_agentExecutionByMQuery"),
  updateSys_agentExecutionById: require("./updateSys_agentExecutionById"),
  updateSys_agentExecutionByIdList: require("./updateSys_agentExecutionByIdList"),
  updateSys_agentExecutionByQuery: require("./updateSys_agentExecutionByQuery"),
  updateSys_agentExecutionByMQuery: require("./updateSys_agentExecutionByMQuery"),
  deleteSys_agentExecutionById: require("./deleteSys_agentExecutionById"),
  deleteSys_agentExecutionByQuery: require("./deleteSys_agentExecutionByQuery"),
  deleteSys_agentExecutionByMQuery: require("./deleteSys_agentExecutionByMQuery"),
};
