module.exports = {
  createFoodItem: require("./createFoodItem"),
  createBulkFoodItem: require("./createBulkFoodItem"),
  getIdListOfFoodItemByField: require("./getIdListOfFoodItemByField"),
  getFoodItemById: require("./getFoodItemById"),
  getFoodItemAggById: require("./getFoodItemAggById"),
  getFoodItemListByQuery: require("./getFoodItemListByQuery"),
  getFoodItemListByMQuery: require("./getFoodItemListByMQuery"),
  getFoodItemStatsByQuery: require("./getFoodItemStatsByQuery"),
  getFoodItemStatsByMQuery: require("./getFoodItemStatsByMQuery"),
  getFoodItemByQuery: require("./getFoodItemByQuery"),
  getFoodItemByMQuery: require("./getFoodItemByMQuery"),
  updateFoodItemById: require("./updateFoodItemById"),
  updateFoodItemByIdList: require("./updateFoodItemByIdList"),
  updateFoodItemByQuery: require("./updateFoodItemByQuery"),
  updateFoodItemByMQuery: require("./updateFoodItemByMQuery"),
  deleteFoodItemById: require("./deleteFoodItemById"),
  deleteFoodItemByQuery: require("./deleteFoodItemByQuery"),
  deleteFoodItemByMQuery: require("./deleteFoodItemByMQuery"),
};
